### PR TITLE
Fix IndexOutOfRangeExceptions from IsMultiSigContract

### LINKED ISSUE #1889: IsMultiSigContract() helper function can throw exceptions
**Summary or problem description**
 "IsMultiSigContract()" can throw `IndexOutOfRangeExceptions` on corrupt data.

The following cases throw IndexOutOfRangeExceptions
1. 
```C#
            var case1 = new byte[]
            {
                0, 2, 12, 33, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
                221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 12, 33, 255, 255, 255, 255,
                255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
                255, 255, 255, 255, 255, 255, 255, 255, 0,
            };
            case1.IsMultiSigContract();

```
   at
https://github.com/neo-project/neo/blob/8879886f8fb694cd2f274cca7675442b3996d812/src/neo/SmartContract/Helper.cs#L83

2. 
```C#
            var case2 = new byte[]
            {
                18, 12, 33, 2, 111, 240, 59, 148, 146, 65, 206, 29, 173, 212, 53, 25, 230, 150, 14, 10, 133, 180, 26,
                105, 160, 92, 50, 129, 3, 170, 43, 206, 21, 148, 202, 22, 12, 33, 2, 111, 240, 59, 148, 146, 65, 206,
                29, 173, 212, 53, 25, 230, 150, 14, 10, 133, 180, 26, 105, 160, 92, 50, 129, 3, 170, 43, 206, 21, 148,
                202, 22, 18
            };
            case2.IsMultiSigContract();
```
   at
https://github.com/neo-project/neo/blob/8879886f8fb694cd2f274cca7675442b3996d812/src/neo/SmartContract/Helper.cs#L97

**Do you have any solution you want to propose?**
I'm hoping to see the function be more resilient and have no exceptions thrown

case 1 can be solved by adding a size check
```C#
if (script.Length <= i + 1 || n != script[++i])
```

case 2 can be solved by moving 
https://github.com/neo-project/neo/blob/8879886f8fb694cd2f274cca7675442b3996d812/src/neo/SmartContract/Helper.cs#L99
2 lines up and checking for a length 6 instead of 4

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- VM
- Other: wallet

### PR DESCRIPTION
**Pull request by shargon**
Close #1889

### CODE REVIEW

**Review by erikzhang — DISMISSED** [review]

File: tests/neo.UnitTests/SmartContract/UT_Helper.cs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+            Assert.IsFalse(case1.IsMultiSigContract());
+
+            var case2 = new byte[]
+            {
+                18, 12, 33, 2, 111, 240, 59, 148, 146, 65, 206, 29, 173, 212, 53, 25, 230, 150, 14, 10, 133, 180, 26,
+                105, 160, 92, 50, 129, 3, 170, 43, 206, 21, 148, 202, 22, 12, 33, 2, 111, 240, 59, 148, 146, 65, 206,
+                29, 173, 212, 53, 25, 230, 150, 14, 10, 133, 180, 26, 105, 160, 92, 50, 129, 3, 170, 43, 206, 21, 148,
+                202, 22, 18
+            };
+            case2.IsMultiSigContract();
```
Comment (ixje) [inline tests/neo.UnitTests/SmartContract/UT_Helper.cs:28]:
```suggestion
            Assert.IsFalse(case2.IsMultiSigContract());
```

**Review by ixje — CHANGES_REQUESTED** [review]

**Review by erikzhang — APPROVED** [review]
