### PR TITLE
[`Fix`]: try to fix account.Lock check

### LINKED ISSUE #3789: No check whether the account is locked when signing consensus messages
**Describe the bug**

A problem found in #3773(but not related to this PR).

According to  https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki#user-content-Account
> lock indicates whether the account is locked by the user. The client shouldn't spend the funds in a locked account.

The `Wallet.MakeTransaction` method has a check for the `Lock` tag.
https://github.com/neo-project/neo/blob/108aa87fddb726a519e2370065c56c994cd57677/src/Neo/Wallets/Wallet.cs#L475

But no check when sign consensus message
https://github.com/neo-project/neo/blob/108aa87fddb726a519e2370065c56c994cd57677/src/Neo/Wallets/Wallet.cs#L598

https://github.com/neo-project/neo/blob/108aa87fddb726a519e2370065c56c994cd57677/src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs#L251

`neo-go` has a check for the `Lock` tag:
https://github.com/nspcc-dev/neo-go/blob/0d8c751e50951ad84cec8b89cf6ea1a9e0f4f878/pkg/consensus/consensus.go#L444

### PR DESCRIPTION
**Pull request by nan01ab**
# Description

Try to fix account.Lock check issue.

Fixing this issue may require more discussion.
 Especially in case of multi-sig and changes in api behavior.

Fixes #3789

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/Neo/Wallets/Wallet.cs [hunk 1]
```diff
@@ -604,24 +604,23 @@ public bool Sign(ContractParametersContext context)
...
             {
-                WalletAccount account = GetAccount(scriptHash);
-
+                var account = GetAccount(scriptHash);
                 if (account != null)
                 {
-                    // Try to sign self-contained multiSig
-
-                    Contract multiSigContract = account.Contract;
+                    if (account.Lock) continue;
```
Comment (cschuchardt88) [inline src/Neo/Wallets/Wallet.cs:610]: Maybe an exception is best here `AccessDeniedException`. This would fix problems with users not knowing the reason why `Sign` is returning `false`. Please update the description as well.

**Comment by cschuchardt88** [comment]
Should this apply to `contract` based accounts? These are on chain contracts, that have their own `verify` method.

**Review by shargon — APPROVED** [review]

**Review by Jim8y — APPROVED** [review]

File: src/Neo/Wallets/Wallet.cs (hunk 1 above)
Comment (cschuchardt88) [reply src/Neo/Wallets/Wallet.cs:610]: I have no good answer for you 😞

**Comment by cschuchardt88** [comment]
> no multi-sig is used now, and `neo-go` doesn't have this feature too.

1. we don't follow  `neoGo`, they follow us.
2. This is core, we follow NEPs to a `Tee`.
3. Your mistaken about that

https://github.com/nspcc-dev/neo-go/blob/0d8c751e50951ad84cec8b89cf6ea1a9e0f4f878/pkg/wallet/account.go#L271-L273

**Comment by cschuchardt88** [comment]
Let just not encrypt wallet password next too?
