### PR TITLE
Fix CallFlags for native contracts and syscalls

### LINKED ISSUE #2316: Allow `Transfer` to read states
**Describe the bug**
`ReadStates` and `WriteStates` are currently different flags and the latter doesn't imply the former. I think this is a bit misleading, because in most cases we use `WriteStates` read is also needed. This can lead to behavior described here https://github.com/nspcc-dev/neo-go/issues/1725 . 

**Solution**
I can think of two of them:
1. Make `WriteStates` require `ReadStates` (rename `States` to `WriteStates`). `States` is currently not used, so I think it makes sense.
2. Replace `WriteStates` with `States` in `Transfer` and possibly some other methods with callbacks (`deploy` and `update` come to mind immediately).

I prefer first solution.

**To Reproduce**
Try to read storage in `onPayment` method, like here https://github.com/nspcc-dev/neo-go/issues/1725

**Expected behavior**
`onPayment` executes correctly.

### PR DESCRIPTION
**Pull request by erikzhang**
Close #2316

### CODE REVIEW

**Comment by erikzhang** [comment]
@shargon @fyrchik

File: src/neo/SmartContract/Native/NonfungibleToken.cs [hunk 1]
```diff
@@ -137,7 +137,7 @@ protected IIterator TokensOf(DataCache snapshot, UInt160 owner)
             return new ArrayWrapper(tokens.Select(p => (StackItem)p).ToArray());
         }
 
-        [ContractMethod(CpuFee = 1 << 17, StorageFee = 50, RequiredCallFlags = CallFlags.WriteStates | CallFlags.AllowNotify)]
+        [ContractMethod(CpuFee = 1 << 17, StorageFee = 50, RequiredCallFlags = CallFlags.States | CallFlags.AllowNotify)]
```
Comment (roman-khimov) [inline src/neo/SmartContract/Native/NonfungibleToken.cs:140]: Not directly related, but I think `AllowCall` is missing here for proper `onNEP11Payment`.

File: src/neo/SmartContract/ApplicationEngine.Storage.cs [hunk 2]
```diff
@@ -15,9 +15,9 @@ partial class ApplicationEngine
...
         public static readonly InteropDescriptor System_Storage_Get = Register("System.Storage.Get", nameof(Get), 1 << 15, CallFlags.ReadStates);
         public static readonly InteropDescriptor System_Storage_Find = Register("System.Storage.Find", nameof(Find), 1 << 15, CallFlags.ReadStates);
-        public static readonly InteropDescriptor System_Storage_Put = Register("System.Storage.Put", nameof(Put), 0, CallFlags.WriteStates);
-        public static readonly InteropDescriptor System_Storage_PutEx = Register("System.Storage.PutEx", nameof(PutEx), 0, CallFlags.WriteStates);
-        public static readonly InteropDescriptor System_Storage_Delete = Register("System.Storage.Delete", nameof(Delete), 0, CallFlags.WriteStates);
+        public static readonly InteropDescriptor System_Storage_Put = Register("System.Storage.Put", nameof(Put), 0, CallFlags.States);
+        public static readonly InteropDescriptor System_Storage_PutEx = Register("System.Storage.PutEx", nameof(PutEx), 0, CallFlags.States);
+        public static readonly InteropDescriptor System_Storage_Delete = Register("System.Storage.Delete", nameof(Delete), 0, CallFlags.States);
```
Comment (roman-khimov) [inline src/neo/SmartContract/ApplicationEngine.Storage.cs:20]: I'd probably leave these as is.

File: src/neo/SmartContract/Native/PolicyContract.cs [hunk 3]
```diff
@@ -53,31 +53,31 @@ public bool IsBlocked(DataCache snapshot, UInt160 account)
             return snapshot.Contains(CreateStorageKey(Prefix_BlockedAccount).Add(account));
         }
 
-        [ContractMethod(CpuFee = 1 << 15, RequiredCallFlags = CallFlags.WriteStates)]
+        [ContractMethod(CpuFee = 1 << 15, RequiredCallFlags = CallFlags.States)]
```
Comment (roman-khimov) [inline src/neo/SmartContract/Native/PolicyContract.cs:56]: And these simple setters can probably also work fine with write only. Although regular contract couldn't do that without read permission just because `GetContext` requires it.

**Review by roman-khimov — COMMENTED** [review]
We might as well make `GetContext` require `States` (with `GetReadOnlyContext` requiring `ReadStates` only), although it can make writing simple getters more complex (it's very convenient to do `GetContext` in the `_initialize` and use it everywhere).

**Review by shargon — DISMISSED** [review]

File: src/neo/SmartContract/Native/NonfungibleToken.cs (hunk 1 above)
Comment (shargon) [reply src/neo/SmartContract/Native/NonfungibleToken.cs:140]: Yes, we should add it

File: src/neo/SmartContract/Native/ContractManagement.cs [hunk 4]
```diff
@@ -229,7 +229,7 @@ private void Update(ApplicationEngine engine, byte[] nefFile, byte[] manifest, S
             engine.SendNotification(Hash, "Update", new VM.Types.Array { contract.Hash.ToArray() });
         }
 
-        [ContractMethod(CpuFee = 1 << 15, RequiredCallFlags = CallFlags.WriteStates | CallFlags.AllowNotify)]
+        [ContractMethod(CpuFee = 1 << 15, RequiredCallFlags = CallFlags.States | CallFlags.AllowNotify)]
```
Comment (erikzhang) [inline src/neo/SmartContract/Native/ContractManagement.cs:232]: I think we don't need `ReadStates` for `Destroy`. Because it only deletes data, not reads.

File: src/neo/SmartContract/Native/NonfungibleToken.cs (hunk 1 above)
Comment (erikzhang) [reply src/neo/SmartContract/Native/NonfungibleToken.cs]: Fixed.

File: src/neo/SmartContract/ApplicationEngine.Storage.cs (hunk 2 above)
Comment (erikzhang) [reply src/neo/SmartContract/ApplicationEngine.Storage.cs:20]: We need to read the `IsConstant` field before writing. Do we need `IsConstant`? Maybe we can remove it.

File: src/neo/SmartContract/Native/PolicyContract.cs (hunk 3 above)
Comment (erikzhang) [reply src/neo/SmartContract/Native/PolicyContract.cs:56]: `CheckCommittee()` needs to call `GetCommittee()`, which needs `ReadStates`.

File: src/neo/SmartContract/Native/ContractManagement.cs (hunk 4 above)
Comment (shargon) [reply src/neo/SmartContract/Native/ContractManagement.cs:232]: First read the contract in order to check if exists

**Review by shargon — DISMISSED** [review]

File: src/neo/SmartContract/ApplicationEngine.Storage.cs (hunk 2 above)
Comment (erikzhang) [reply src/neo/SmartContract/ApplicationEngine.Storage.cs:20]: @shargon @roman-khimov What do you think?

Comment (roman-khimov) [reply src/neo/SmartContract/ApplicationEngine.Storage.cs:20]: It can be a significant storage item simplification, but we'll loose a safety feature at the same time that I can't see any substitute for (other than a separate "constant storage context", but that's not really better than the flag we have at the moment). But I'm not sure it's really used by contracts.

Comment (erikzhang) [reply src/neo/SmartContract/ApplicationEngine.Storage.cs:20]: I think it's never used.

**Review by shargon — APPROVED** [review]
