### PR TITLE
[master-2.x] fix block_cache

### LINKED ISSUE #2088: [master-2.x] InvPayload contains null hash
image

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #2088

This issue should have been caused by multithread read/write, as `block_cache` is called by both `Blockchain` and `TaskManager`.

### CODE REVIEW

**Review by shargon — APPROVED** [review]
Good to know that you find the root cause of the issue
https://github.com/neo-project/neo/pull/2089#issuecomment-733665431

**Review by vncoelho — DISMISSED** [review]

File: neo/Ledger/Blockchain.cs [hunk 1]
```diff
@@ -120,8 +121,8 @@ public class FillCompleted { }
         private readonly NeoSystem system;
         private readonly List<UInt256> header_index = new List<UInt256>();
         private uint stored_header_count = 0;
-        private readonly Dictionary<UInt256, Block> block_cache = new Dictionary<UInt256, Block>();
-        private readonly Dictionary<uint, LinkedList<Block>> block_cache_unverified = new Dictionary<uint, LinkedList<Block>>();
+        private readonly ConcurrentDictionary<UInt256, Block> block_cache = new ConcurrentDictionary<UInt256, Block>();
+        private readonly ConcurrentDictionary<uint, LinkedList<Block>> block_cache_unverified = new ConcurrentDictionary<uint, LinkedList<Block>>();
```
Comment (shargon) [inline neo/Ledger/Blockchain.cs]: If `block_cache_unverified` it's not used in different threads, we can revert this change and merge it

**Review by shargon — APPROVED** [review]

**Review by shargon — APPROVED** [review]
Test pass, but coverals it's failing

**Comment by Qiao-Jin** [comment]
> Test pass, but coverals it's failing

It seems something is wrong with coverall-check system

**Comment by shargon** [comment]
> It seems something is wrong with coverall-check system

We can fix it later, or maybe it's temporal
