### PR TITLE
Fix #4316

### LINKED ISSUE #4314: Inconsistent behaviours for  `VerifyWithEd25519` and `VerifyWithECDsa`.
The are several inconsistent behaviours for  `VerifyWithEd25519` and `VerifyWithECDsa`:

 Inconsistent behaviours:
* PublicKey
  * verifyWithECDsa: exception if the public key is invalid or null; 
  * verifyWithEd25519: exception if the public key is null and result is always false if the public key is invalid;

* Signature
  * verifyWithECDsa: result is false if the signature is invalid or null;
  * verifyWithEd25519: result is false if the signature is invalid, exception if the signature is null;

* Message
  * verifyWithECDsa: result is true if the message is null and signature is valid;
  * verifyWithEd25519: result is always false if the message is null even if signature is valid;

Weird behaviours:
 `verifyWithECDsa`  has different exceptions if NamedCurveHash is invalid:
* Overflow exception if NamedCurveHash is greater than 255;
* KeyNotFoundException if NamedCurveHash is less than 255 but is invalid.

`verifyWithECDsa ` has different exceptions if PublicKey is invalid:
* FormatException if PublicKey is not null or empty but invalid;
* IndexOutOfRangeException if PublicKey is null or empty(should be FormatException)

These behaviors make it difficult for users to use and make neo seem unprofessional.

### LINKED ISSUE #4316: `VerifySignature` has inconsistent  behaves across different platforms.
`VerifySignature` has inconsistent  behaves across different platforms.
For example:
if the public key is invalid(but the format is ok):

macOS: the result is false;
Windows: PlatformNotSupportedException;
Linux: Interop+Crypto+OpenSslCryptographicException

### PR DESCRIPTION
**Pull request by erikzhang**
# Description

Fixes #4316
Fixes #4314

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [ ] Unit Testing
- [ ] Run Application
- [ ] Local Computer Tests
- [x] No Testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/Neo/SmartContract/Native/CryptoLib.cs [hunk 1]
```diff
@@ -114,15 +114,8 @@ public static byte[] Keccak256(byte[] data)
...
-            try
-            {
-                var ch = s_curves[curveHash];
-                return Crypto.VerifySignature(message, signature, pubkey, ch.Curve, ch.HashAlgorithm);
-            }
-            catch (ArgumentException)
-            {
-                return false;
-            }
+            var ch = s_curves[curveHash];
```
Comment (shargon) [inline src/Neo/SmartContract/Native/CryptoLib.cs]: The problem removing the try/catch is that different implementation (neo go for example) may not throw and exception and return false, could you check it @roman-khimov ?

File: src/Neo/SmartContract/Native/CryptoLib.cs [hunk 2]
```diff
@@ -153,22 +138,15 @@ public static bool VerifyWithECDsaV0(byte[] message, byte[] pubkey, byte[] signa
         public static bool VerifyWithEd25519(byte[] message, byte[] pubkey, byte[] signature)
         {
             if (signature.Length != Ed25519.SignatureSize)
-                return false;
+                throw new FormatException($"Signature size should be {Ed25519.SignatureSize}");
```
Comment (Wi1l-B0t) [inline src/Neo/SmartContract/Native/CryptoLib.cs]: This will make it incompatible with previous behavior.

`VerifyWithECDsa` returns false if signature.length is wrong,
but `VerifyWithEd25519` will throw exception if apply this patch.

File: src/Neo/SmartContract/Native/CryptoLib.cs (hunk 1 above)
Comment (Wi1l-B0t) [inline src/Neo/SmartContract/Native/CryptoLib.cs]: `ArgumentException` if  `curveHash` not exists.

`KeyNotFoundException` now.

Comment (AnnaShaleva) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: We may adjust these handlers if needed.

However, you're right in that it's a breaking change and it may lead to a state diff, so we either need to move it under yet another hardfork or at least to check that it doesn't introduce state diff to existing mainnet/testnet.

File: src/Neo/SmartContract/Native/CryptoLib.cs (hunk 2 above)
Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: Now `VerifyWithECDsa` throws exception too.

File: src/Neo/SmartContract/Native/CryptoLib.cs (hunk 1 above)
Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: It throws `NotSupportedException` now.

File: src/Neo/SmartContract/Native/CryptoLib.cs (hunk 2 above)
Comment (Wi1l-B0t) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: This interface behavior is different, which may lead to different contract running results if no hardfork.

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: We can add hardfork in master-n3.

Comment (Wi1l-B0t) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: A hard fork is also needed for n4?
because n4 and n3 are compatible.

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: According to our current development model, compatibility is not considered for the master branch.

Comment (vncoelho) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: As I see, we can remover all hard forks from master branch, right?

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs]: Yes. I will do it later.

File: src/Neo/Cryptography/Crypto.cs [hunk 3]
```diff
@@ -29,10 +26,6 @@ public static class Crypto
     private static readonly BigInteger s_prime = new(1,
         Hex.Decode("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F"));
 
-    private static readonly ECDsaCache s_cacheECDsa = [];
-    private static readonly bool s_isOSX = RuntimeInformation.IsOSPlatform(OSPlatform.OSX);
-    private static readonly ECCurve s_secP256k1 = ECCurve.CreateFromFriendlyName("secP256k1");
```
Comment (vncoelho) [inline src/Neo/Cryptography/Crypto.cs:34]: maybe this was more expensive especially on Windows CNG and macOS Security, right?
So, no much real change for real operations.

File: tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractGroup.cs [hunk 4]
```diff
@@ -45,7 +45,7 @@ public void TestIsValid()
         ContractGroup contractGroup = new()
         {
             PubKey = keyPair.PublicKey,
-            Signature = new byte[20]
+            Signature = new byte[64]
```
Comment (vncoelho) [inline tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractGroup.cs:48]: general fix on this UT, right? not related to this PR @shargon

File: src/Neo/Cryptography/Crypto.cs (hunk 3 above)
Comment (vncoelho) [reply src/Neo/Cryptography/Crypto.cs:34]: Why the cached needs to be removed?

Comment (erikzhang) [reply src/Neo/Cryptography/Crypto.cs:34]: Because we now uniformly use BouncyCastle. And they are not used in BouncyCastle.

File: tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractGroup.cs (hunk 4 above)
Comment (erikzhang) [reply tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractGroup.cs:48]: If it's 20, we won't be able to test the code we want; it will judge from the beginning that the parameter does not meet the format requirements.

File: src/Neo/SmartContract/Native/CryptoLib.cs [hunk 5]
```diff
@@ -134,21 +128,14 @@ public static bool VerifyWithECDsa(byte[] message, byte[] pubkey, byte[] signatu
...
-            var verifier = new Ed25519Signer();
-            verifier.Init(false, new Ed25519PublicKeyParameters(pubkey, 0));
-            verifier.BlockUpdate(message, 0, message.Length);
-            return verifier.VerifySignature(signature);
-        }
-        catch (Exception)
-        {
-            return false;
-        }
+        var verifier = new Ed25519Signer();
```
Comment (shargon) [inline src/Neo/SmartContract/Native/CryptoLib.cs:136]: In general I prefer to return false if there is any exception. for example if the pubKey it's infinite, maybe go implementation return false, and here will throw an exception

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: Throwing an exception lets us know where the error is, making it easier for us to pinpoint the problem.

Comment (Wi1l-B0t) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: > In general I prefer to return false if there is any exception. for example if the pubKey it's infinite, maybe go implementation return false, and here will throw an exception

Agree. 
It's easier to use.

Comment (Wi1l-B0t) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: > Throwing an exception lets us know where the error is, making it easier for us to pinpoint the problem.

Can add logs.

Comment (shargon) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: I know, but the execution must be deterministic, and in this syscalls where an external library is used, we should try to avoid some errors

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: Now we use Bouncycastle, which has good cross-platform consistency.

Comment (Wi1l-B0t) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: There may be differences between different Bouncycastle  versions.

Comment (shargon) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: Bouncycastle don't need deterministic between platforms

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: If the argument format does not meet the requirements, we throw an exception; we return `false` only if everything is normal but the signature verification itself fails. This logic is consistent with all other methods.

Comment (Jim8y) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: we dont need to know what happend, and where is the problem, we only need to know if the verification is failed or not.

Comment (Jim8y) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: > se Bouncycastle, which has good cross-platform consistency.

this is not guaranteed, and cross-platform consistency can be rooted from the fundamental csharp/dotnet. Even official BigInteger can have problems, previously we identified a bug in BigInteger and reported to dotnet, and they fixed that. Thus we should make the state as simple as possible, such that we can use tests to cover all states (as long as its not right, all wrong).

Comment (erikzhang) [reply src/Neo/SmartContract/Native/CryptoLib.cs:136]: I think we should keep a clear distinction between **argument errors** and **normal verification failures**.

* **Invalid arguments (wrong length, malformed key, unsupported curve)** → this is a *precondition violation*, so the syscall should FAULT.
* **Valid arguments but signature mismatch** → return `false`.

One key point:
**We should not let the return type dictate error semantics.**
If the method returned an object instead of `bool`, we would *still* validate arguments and throw on invalid input. The API should behave consistently, regardless of whether the return type happens to be `boolean`.

If all errors collapse into `false`, then caller bugs (wrong length, wrong curve, corrupted key) become indistinguishable from a real “signature mismatch”, which hurts debugging and hides logic issues.

**Comment by superboyiii** [comment]
`master-n3` need this as well.

**Comment by Wi1l-B0t** [comment]
> `master-n3` need this as well.

For n3, a hard fork is needed.

**Comment by shargon** [comment]
@ajara87 could you port this to N3?
