### PR TITLE
GetBlocks by block index

### LINKED ISSUE #1378: The new mechanism of block synchronization using Index.
**Background**

Thanks to @ixje @erikzhang @vncoelho @jsolman @shargon for the discussion in #522, #1138, #781, and added a new p2p message for `GetBlockData`. 
Now, we will discuss the new mechanism of block synchronization using Index.

**Do you have any solution you want to propose?**

We recommend creating a new `SyncManager` class that manages synchronization, while `TaskManager` handles `Inv` messages. The overall mechanism process is as follows:
 

Process:
1.	Get the latest block height of remotenode through `PingPong` messages.

2.	Calculate the block segments to be synchronized based on the current local block height and remotenode block height. According to the task interval rule (for example, each task can synchronize a maximum of 50 blocks), the block segment is divided into several synchronous tasks. Select a suitable node according to the task assignment rule and assign synchronous task to it. Save the startIndex, endIndex, task time and other information of the synchronization task. Send the GetBlockdata request.

3.	Each task maintains a `BitArray` to record the received blocks’ index. Find the corresponding task for each received block, and set the bit corresponding to the index of the received block to true. Then, tell the received block to Blockchain.

4.	`Blockchain` verifies the block and persists it, then tell the index of the persisted block to `SyncManager`.

5.	`SyncManager` checks the index of the persisted block. If the index reaches the `endIndex` of a task, check the list of all tasks, delete the corresponding completed task, and assign a new task to the node.

Task assignment rule:
    Assign task to the node with the lowest number of tasks.

Task interval rule: 
    `startIndex` is the `endIndex` of the previous task + 1; `EndIndex` is the height that is greater than and nearest to `startIndex` and divisible by 50.

Exception handling:

6.	The Timer will check the task timeout, and if the task is timed out, the corresponding task will be re-assigned to other nodes.

7.	If blockchain receives a invalid block, tell to `SyncManager` and reassign the task to other node.(the node sending the invalid block can be marked as a bad node)

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Ledger
- P2P (TCP)

### PR DESCRIPTION
**Pull request by ShawnYun**
Closes #1378.
As the discussion at #1378 ,we will modify the synchronization mechanism in two steps:

Use index directly for synchronization;
Add the assessment of node health.
This PR is the draft of the first step, which is mainly modified in the following aspects:

Deleted the original logic of synchronous block header;
Modified the processing of receiving the new block in Blockchain;
SyncManager has been added to manage synchronization tasks.
If you have any comments, please let me know

### CODE REVIEW

File: src/neo/NeoSystem.cs [hunk 1]
```diff
@@ -36,6 +37,7 @@ public NeoSystem(string storageEngine = null)
             this.Blockchain = ActorSystem.ActorOf(Ledger.Blockchain.Props(this, store));
             this.LocalNode = ActorSystem.ActorOf(Network.P2P.LocalNode.Props(this));
             this.TaskManager = ActorSystem.ActorOf(Network.P2P.TaskManager.Props(this));
+            this.SyncManager = ActorSystem.ActorOf(Network.P2P.SyncManager.Props(this));
```
Comment (vncoelho) [inline src/neo/NeoSystem.cs]: Omg, SyncManager? aheuaheuaheuaea
Specialized in syncing a node up-to-date?

Sounds like a subtask of TaskManager.

Comment (Tommo-L) [reply src/neo/NeoSystem.cs]: > Sounds like a subtask of TaskManager.

Yes, we're trying to use block index for synchronization 😂

**Comment by Tommo-L** [comment]
@erikzhang @ixje @vncoelho @shargon  Could help review it, plz

**Comment by ixje** [comment]
I had a quick look and the first thing I noticed is that there is a new `MessageCommand.BlockData`. Why do we need this instead of using the existing `Block`?
https://github.com/neo-project/neo/blob/d9d54b5dfe44e41561ff729b08b9b7caf1f0d6b9/src/neo/Network/P2P/MessageCommand.cs#L40

Both messages deliver the same payload (of type `Block`)

**Comment by ShawnYun** [comment]
@ixje The `MessageCommand.Block`  is used to handle the inv messages. So we need a new command 'MessageCommand.BlockData' to handle the new sync message.  Although their payloads both are blocks, they have different methods:   `OnInventoryReceived` and `OnBlockDataReceived`.

**Comment by ixje** [comment]
> @ixje The `MessageCommand.Block` is used to handle the inv messages. 

@ShawnYun the intended sequence behind #1138 is 
- `Client` requests _n_-blocks from `Node` using `MessageCommand.GetBlockData` + `GetBlockDataPayload`
- `Node` replies with _n_-`MessageCommand.Block` messages. 

`Client` can now simply re-use all existing `MessageCommand.Block` logic. 

It feels wrong to add a new network message to the P2P protocol just because the client design needs to handle blocks received as a result from `INV` messages different from those received from `GetBlockData` messages.

File: src/neo/Network/P2P/ProtocolHandler.cs [hunk 2]
```diff
@@ -91,6 +91,9 @@ private void OnMessage(Message msg)
                 case MessageCommand.Block:
                     OnInventoryReceived((Block)msg.Payload);
                     break;
+                case MessageCommand.BlockData:
+                    OnBlockDataReceived((Block)msg.Payload);
```
Comment (shargon) [inline src/neo/Network/P2P/ProtocolHandler.cs]: What is the difference with `Block`?

File: src/neo/Network/P2P/RemoteNode.cs [hunk 3]
```diff
@@ -196,6 +197,7 @@ private void OnVerack()
         {
             verack = true;
             system.TaskManager.Tell(new TaskManager.Register { Version = Version });
```
Comment (shargon) [inline src/neo/Network/P2P/RemoteNode.cs]: reuse the same Register object?

File: src/neo/Network/P2P/SyncManager.cs [hunk 4]
```diff
@@ -0,0 +1,261 @@
...
+
+        private bool ReSync(SyncSession oldSession, Task task)
+        {
+            Random rand = new Random();
+            SyncSession session = sessions.Values.Where(p => p != oldSession && p.Tasks.Count <= maxTasksPerSession && p.LastBlockIndex >= task.EndIndex).OrderBy(p => p.Tasks.Count).ThenBy(s => rand.Next()).FirstOrDefault();
+            if (session == null)
+                return false;
+            int count = (int)(task.EndIndex - task.StartIndex + 1);
+            session.Tasks.Add(new Task { StartIndex = task.StartIndex, EndIndex = task.EndIndex, IndexArray = new BitArray(count), Time = DateTime.UtcNow });
+            session.RemoteNode.Tell(Message.Create(MessageCommand.GetBlockData, GetBlockDataPayload.Create(task.StartIndex, (ushort)count)));
```
Comment (shargon) [inline src/neo/Network/P2P/SyncManager.cs]: I think that we can set in a dictionary wich blocks we want to retrieve in order to use the same message, when we receive a block, check if was requested by the syncmanager or not.

**Comment by Tommo-L** [comment]
@ixje  Currently, we just use `SyncManager` for fast synchronization, and keep the `inv-getdata-block` mode for normal synchronization.  
But as you said, we can completely abandon the `inv-block` synchronization mechanism, we need to think it more.

File: src/neo/Network/P2P/ProtocolHandler.cs (hunk 2 above)
Comment (ShawnYun) [reply src/neo/Network/P2P/ProtocolHandler.cs]: We are discussing the problem，Maybe we should delete it.

**Comment by ixje** [comment]
@Tommo-L can't the `OnInventoryReceived` be extended to also notify syncmanager? 
https://github.com/neo-project/neo/blob/d9d54b5dfe44e41561ff729b08b9b7caf1f0d6b9/src/neo/Network/P2P/ProtocolHandler.cs#L316-L322

I don't have a clear picture of the task/sync managers inner workings, but I'm assuming the following could happen from a high level view;

- sync manager detects local chain is behind remote chain. Create a task to get blocks
- a block is received -> sync manager and task manager get notified. 
    - TaskManager can't find a related task and thus ignores the notification 
    - Sync manager finds the outstanding task in its list and removes it

**Comment by Tommo-L** [comment]
Yes, we can do this. I want to optimize again, merge TaskManager and SyncManager, and discard inv-block synchronization.

**Comment by ixje** [comment]
> Yes, we can do this. I want to optimize again, merge TaskManager and SyncManager, and discard inv-block synchronization.

Perhaps this is the easiest solution (to keep both mechanisms) -> https://github.com/neo-project/neo/pull/1397#discussion_r364124475

File: src/neo/Network/P2P/ProtocolHandler.cs (hunk 2 above)
Comment (erikzhang) [reply src/neo/Network/P2P/ProtocolHandler.cs]: Yes, we should delete it.

File: src/neo/Ledger/Blockchain.cs [hunk 5]
```diff
@@ -292,78 +291,30 @@ private RelayResultReason OnNewBlock(Block block)
...
-                    uint extraBlocks = (15000 - MillisecondsPerBlock) / 1000;
-
-                    if (blocksPersisted++ < blocksToPersistList.Count - (2 + Math.Max(0, extraBlocks))) continue;
-                    // Empirically calibrated for relaying the most recent 2 blocks persisted with 15s network
-                    // Increase in the rate of 1 block per second in configurations with faster blocks
-
-                    if (blockToPersist.Index + 100 >= header_index.Count)
-                        system.LocalNode.Tell(new LocalNode.RelayDirectly { Inventory = blockToPersist });
+                    system.SyncManager.Tell(new SyncManager.InvalidBlockIndex { InvalidIndex = block.Index });
+                    return RelayResultReason.Invalid;
```
Comment (vncoelho) [inline src/neo/Ledger/Blockchain.cs]: In this case we should detect who was the Peer who sent this invalid block.

File: src/neo/Ledger/Blockchain.cs [hunk 6]
```diff
@@ -258,8 +252,13 @@ private void AddUnverifiedBlockToCache(Block block)
             {
                 blocks = new LinkedList<Block>();
                 block_cache_unverified.Add(block.Index, blocks);
+                return;
```
Comment (vncoelho) [inline src/neo/Ledger/Blockchain.cs]: I think that the `block` need to be added to `blocks` being adding.
```cs
blocks = new LinkedList<Block>();
blocks.AddLast(block);
block_cache_unverified.Add(block.Index, blocks);
```

File: src/neo/Ledger/Blockchain.cs [hunk 7]
```diff
@@ -292,76 +294,28 @@ private RelayResultReason OnNewBlock(Block block)
...
-                foreach (Block blockToPersist in blocksToPersistList)
+                if (!block.Verify(currentSnapshot))
                 {
-                    block_cache_unverified.Remove(blockToPersist.Index);
-                    Persist(blockToPersist);
-
-                    // 15000 is the default among of seconds per block, while MilliSecondsPerBlock is the current
-                    uint extraBlocks = (15000 - MillisecondsPerBlock) / 1000;
-
-                    if (blocksPersisted++ < blocksToPersistList.Count - (2 + Math.Max(0, extraBlocks))) continue;
```
Comment (vncoelho) [inline src/neo/Ledger/Blockchain.cs]: @ShawnYun, this extra relaying will be removed, right?
Perhaps this will not be needed anymore, all right @jsolman ?

File: src/neo/Network/P2P/RemoteNode.cs (hunk 3 above)
Comment (vncoelho) [reply src/neo/Network/P2P/RemoteNode.cs]: I prefer if we remove and merge SyncManager with TaskManager, as @Tommo-L mentioned recently.
What are the advantages of separated ones?

File: src/neo/Network/P2P/SyncManager.cs [hunk 8]
```diff
@@ -0,0 +1,261 @@
...
+        }
+
+        private void OnReceiveInvalidBlockIndex(InvalidBlockIndex invalidBlockIndex)
+        {
+            if (sessions.Count() == 0 || sessions.Values.Where(p => p.HasTask).Count() == 0) return;
+            foreach (SyncSession session in sessions.Values.Where(p => p.HasTask))
+            {
+                for (int i = 0; i < session.Tasks.Count(); i++)
+                {
+                    if (session.Tasks[i].StartIndex <= invalidBlockIndex.InvalidIndex && session.Tasks[i].EndIndex >= invalidBlockIndex.InvalidIndex)
```
Comment (vncoelho) [inline src/neo/Network/P2P/SyncManager.cs]: We need to check if there are more Unverified Candidates to be processed, maybe it was just a spam.

**Comment by ShawnYun** [comment]
All Block tasks are now managed by SyncManager, and Inv tasks are managed by TaskManager. Each RemoteNode has a NodeSession.

File: src/neo/Ledger/Blockchain.cs (hunk 6 above)
Comment (vncoelho) [reply src/neo/Ledger/Blockchain.cs]: @ShawnYun, did you take a look at this?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: @vncoelho Thanks, you are right. Or we can delete this `return`, then the `block` will add to `blocks`?

File: src/neo/Network/P2P/SyncManager.cs (hunk 8 above)
Comment (ShawnYun) [reply src/neo/Network/P2P/SyncManager.cs]: We could deal with it in the next phase. Maintain the health of the remotenodes to avoid attacks.

File: src/neo/Ledger/Blockchain.cs (hunk 7 above)
Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: Now we don't have the `blocksToPersistList`. Perhaps we should discuss this question.

File: src/neo/Ledger/Blockchain.cs (hunk 6 above)
Comment (vncoelho) [reply src/neo/Ledger/Blockchain.cs]: Not sure, @ShawnYun, aheuahuea

File: src/neo/Ledger/Blockchain.cs (hunk 7 above)
Comment (vncoelho) [reply src/neo/Ledger/Blockchain.cs]: This was something that surely increase network overall communication on the P2P.

I think it is good to remove but to keep this logic in mind in case we notice problems on syncing.

File: src/neo/Network/P2P/SyncManager.cs [hunk 9]
```diff
@@ -0,0 +1,284 @@
...
+                case Timer _:
+                    OnTimer();
+                    break;
+                case Terminated terminated:
+                    OnTerminated(terminated.ActorRef);
+                    break;
+            }
+        }
+
+        private bool CheckNodes()
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: Need a better name

File: src/neo/Network/P2P/SyncManager.cs [hunk 10]
```diff
@@ -0,0 +1,284 @@
...
+                }
+                if (sessionWithIndexTask.Item2.IndexArray.Cast<bool>().All(p => p == true))
+                {
+                    totalTasksCount--;
+                }
+            }
+            RequestSync();
+        }
+
+        private bool ReSync(NodeSession oldSession, IndexTask task)
```
[the remark this answers is not in the document]
Comment (ShawnYun) [reply src/neo/Network/P2P/SyncManager.cs]: It was good.

File: src/neo/Network/P2P/SyncManager.cs (hunk 9 above)
Comment (ShawnYun) [reply src/neo/Network/P2P/SyncManager.cs]: How about `NodesHaveTasks()`

File: src/neo/Network/P2P/SyncManager.cs (hunk 8 above)
Comment (vncoelho) [reply src/neo/Network/P2P/SyncManager.cs]: @ShawnYun, can or open an issue with that? Or should I open?
I prefer if you open and keep taking a look at this, you can count with me support.

Comment (ShawnYun) [reply src/neo/Network/P2P/SyncManager.cs]: @vncoelho Thanks, I will open a issue about it.

Comment (ShawnYun) [reply src/neo/Network/P2P/SyncManager.cs]: @vncoelho We can talk about this in #1316

File: src/neo/Network/P2P/SyncManager.cs [hunk 11]
```diff
@@ -0,0 +1,204 @@
...
+        private readonly Dictionary<IActorRef, RemoteNode> nodes = new Dictionary<IActorRef, RemoteNode>();
+        private readonly Dictionary<uint, RemoteNode> receivedBlockIndex = new Dictionary<uint, RemoteNode>();
+        private readonly NeoSystem system;
+        private readonly ICancelable timer = Context.System.Scheduler.ScheduleTellRepeatedlyCancelable(TimerInterval, TimerInterval, Context.Self, new Timer(), ActorRefs.NoSender);
+        private readonly List<uint> failedTasks = new List<uint>();
+
+        private const int MaxTasksCount = 50;
+        private const int PingCoolingOffPeriod = 60; // in secconds.
+
+        private uint highestBlockIndex = 0;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: we can remove this line now.

File: src/neo/Network/P2P/SyncManager.cs [hunk 12]
```diff
@@ -0,0 +1,204 @@
...
+
+        private void OnReceiveInvalidBlockIndex(InvalidBlockIndex invalidBlockIndex)
+        {
+            receivedBlockIndex.TryGetValue(invalidBlockIndex.InvalidIndex, out RemoteNode node);
+            if (node is null) return;
+            node.session.InvalidBlockCount++;
+            node.session.IndexTasks.Remove(invalidBlockIndex.InvalidIndex);
+            receivedBlockIndex.Remove(invalidBlockIndex.InvalidIndex);
+            AssignTask(invalidBlockIndex.InvalidIndex, node.session);
+            return;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: remove this line

File: src/neo/Network/P2P/SyncManager.cs [hunk 13]
```diff
@@ -0,0 +1,204 @@
...
+                    failedTasks.Remove(failedTasks[i]);
+                    continue;
+                }
+                if (!AssignTask(failedTasks[i]))
+                    return;
+            }
+            for (var count = GetTasksCount(); count < MaxTasksCount; count++)
+            {
+                if (lastTaskIndex >= highestBlockIndex) break;
+                uint index = lastTaskIndex + 1;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: lastTaskIndex++

File: src/neo/Network/P2P/SyncManager.cs [hunk 14]
```diff
@@ -0,0 +1,204 @@
...
+            return;
+        }
+
+        private void RequestSync()
+        {
+            if (GetTasksCount() >= MaxTasksCount || nodes.Count() == 0) return;
+            SendPingMessage();
+            highestBlockIndex = nodes.Values.Max(p => p.LastBlockIndex);
+            if (lastTaskIndex == 0)
+                lastTaskIndex = Blockchain.Singleton.Height;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: move the last line to the constructor

File: src/neo/Network/P2P/SyncManager.cs [hunk 15]
```diff
@@ -0,0 +1,204 @@
...
+            for (int i = 0; i < failedTasks.Count(); i++)
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]:
```csharp
foreach(int index of failedTasks)
```

File: src/neo/Network/P2P/SyncManager.cs [hunk 16]
```diff
@@ -0,0 +1,204 @@
...
+            {
+                if (failedTasks[i] <= Blockchain.Singleton.Height)
+                {
+                    failedTasks.Remove(failedTasks[i]);
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: we can move `failedTasks.Remove(persistedIndex)` to `OnReceivePersistedBlockIndex` method.

File: src/neo/Network/P2P/SyncManager.cs [hunk 17]
```diff
@@ -0,0 +1,204 @@
...
+
+        private void OnTerminated(IActorRef actor)
+        {
+            if (!nodes.TryGetValue(Sender, out RemoteNode remoteNode))
+                return;
+            NodeSession session = remoteNode.session;
+            foreach (uint index in session.IndexTasks.Keys)
+                AssignTask(index, session);
+            nodes.Remove(actor);
+            if (GetTasksCount() == 0) lastTaskIndex = 0;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: I think we can remove this line,

File: src/neo/Network/P2P/SyncManager.cs [hunk 18]
```diff
@@ -0,0 +1,204 @@
...
+        }
+
+        private int GetTasksCount()
+        {
+            int count = 0;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: If we remove L151, this method can also be deleted

File: src/neo/Network/P2P/SyncManager.cs [hunk 19]
```diff
@@ -0,0 +1,204 @@
...
+            return count;
+        }
+
+        private bool AssignTask(uint index, NodeSession filterSession = null)
+        {
+            if (nodes.Values.Any(p => p.session.IndexTasks.ContainsKey(index)))
+                return true;
+            Random rand = new Random();
+            RemoteNode remoteNode = nodes.Values.Where(p => p.session != filterSession && p.LastBlockIndex >= index)
+                .OrderBy(p => p.session.IndexTasks.Count).ThenBy(s => rand.Next()).FirstOrDefault();
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: format
```csharp
RemoteNode remoteNode = nodes.Values.Where(p => p.session != filterSession && p.LastBlockIndex >= index)
                .OrderBy(p => p.session.IndexTasks.Count)
                .ThenBy(s => rand.Next())
                .FirstOrDefault();
```

File: src/neo/Network/P2P/SyncManager.cs [hunk 20]
```diff
@@ -0,0 +1,201 @@
...
+                lastTaskIndex++;
+                if (!AssignTask(lastTaskIndex)) break;
+            }
+        }
+
+        private void OnTimer()
+        {
+            RemoteNode[] remoteNodes = nodes.Values.ToArray();
+            foreach (var node in remoteNodes)
+            {
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: Change to 
```csharp
private void OnTimer()
{
     foreach(var remoteNode of nodes.Values)
        .......
}
 ```

File: src/neo/Network/P2P/SyncManager.cs [hunk 21]
```diff
@@ -0,0 +1,201 @@
...
+                }
+                if (!AssignTask(failedTasks[i]))
+                    return;
+            }
+            for (var count = GetTasksCount(); count < MaxTasksCount; count++)
+            {
+                if (lastTaskIndex >= highestBlockIndex) break;
+                lastTaskIndex++;
+                if (!AssignTask(lastTaskIndex)) break;
+            }
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: example 
```csharp
for(var taskCout = GetTasksCount(); taskCount < MaxTasksCount; taskCount++)
{
      if (failedTasks.TryPeek(out int index) && index > Blockchain.Singleton.Height)
            if (!AssignTask(failedTasks[i])) break;

      if (lastTaskIndex >= highestBlockIndex) break;
      if (!AssignTask(++lastTaskIndex)) break;
}
```

File: src/neo/Network/P2P/SyncManager.cs [hunk 22]
```diff
@@ -0,0 +1,201 @@
...
+            if (node is null) return;
+            node.session.InvalidBlockCount++;
+            node.session.IndexTasks.Remove(invalidBlockIndex.InvalidIndex);
+            receivedBlockIndex.Remove(invalidBlockIndex.InvalidIndex);
+            AssignTask(invalidBlockIndex.InvalidIndex, node.session);
+        }
+
+        private void RequestSync()
+        {
+            if (GetTasksCount() >= MaxTasksCount || nodes.Count() == 0) return;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: This line, I think we can remove now.

File: src/neo/Network/P2P/SyncManager.cs [hunk 23]
```diff
@@ -0,0 +1,201 @@
...
+        private class Timer { }
+
+        private static readonly TimeSpan TimerInterval = TimeSpan.FromSeconds(30);
+        private static readonly TimeSpan SyncTimeout = TimeSpan.FromMinutes(1);
+
+        private readonly Dictionary<IActorRef, RemoteNode> nodes = new Dictionary<IActorRef, RemoteNode>();
+        private readonly Dictionary<uint, RemoteNode> receivedBlockIndex = new Dictionary<uint, RemoteNode>();
+        private readonly NeoSystem system;
+        private readonly ICancelable timer = Context.System.Scheduler.ScheduleTellRepeatedlyCancelable(TimerInterval, TimerInterval, Context.Self, new Timer(), ActorRefs.NoSender);
+        private readonly List<uint> failedTasks = new List<uint>();
```
Comment (Tommo-L) [inline src/neo/Network/P2P/SyncManager.cs]: `Queue<uint> failedTasks`

**Comment by shargon** [comment]
This option will remove the previous one?

**Comment by ShawnYun** [comment]
@shargon Yes, Now it will request 1 block per task.

**Comment by shargon** [comment]
Then we need the headers?

**Comment by ShawnYun** [comment]
@shargon We don't need to use headers to synchronize blocks. Just index.

**Comment by Tommo-L** [comment]
Could help have a review again?  @shargon @ixje @vncoelho  
`SyncManager` will only focus on syncing block by block index.
`TaskManager` will only focus on inv task.

After reviewed, we'll add some UTs and invite Erik to review.

**Comment by shargon** [comment]
> We don't need to use headers to synchronize blocks. Just index.

But we will need headers for anything else?

**Comment by Tommo-L** [comment]
> But we will need headers for anything else?

Headers are not removed, but not sync block header now. `BlockChain.cs` will persist headers and clients can request headers from other node by p2p  `MessageCommand.GetHeaders` message.

**Comment by shargon** [comment]
If we don't require headers for sync, maybe we need to remove them?

**Comment by Tommo-L** [comment]
SPV and cross-chain relayer both need headers. Currently, `MessageCommand.GetHeaders` use the hash of header for synchronization, maybe it's better to use the block index.

File: src/neo/Ledger/Blockchain.cs [hunk 24]
```diff
@@ -61,8 +61,7 @@ private class ParallelVerified { public Transaction Transaction; public bool Sho
         private readonly NeoSystem system;
         private readonly List<UInt256> header_index = new List<UInt256>();
         private uint stored_header_count = 0;
-        private readonly Dictionary<UInt256, Block> block_cache = new Dictionary<UInt256, Block>();
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs]: Why this is removed?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: `block_cache` is used to store the correct blocks (block.Index > Height + 1) that have been verified by headers. 
Now we don't synchronize the block headers, so we can't verify that the blocks are correct,.So they are all stored in `unverified_blocks_candidates`.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: But `TaskManager` is not removed, isn't it?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: Now `TaskManager` is used to sync `Tx` and `Consensus` message.

Comment (Tommo-L) [reply src/neo/Ledger/Blockchain.cs]: SyncManager only focus on syncing block by block index.
TaskManager only focus on inv task.

File: src/neo/Ledger/Blockchain.cs [hunk 25]
```diff
@@ -294,78 +295,30 @@ private RelayResultReason OnNewBlock(Block block)
...
-                    // 15000 is the default among of seconds per block, while MilliSecondsPerBlock is the current
-                    uint extraBlocks = (15000 - MillisecondsPerBlock) / 1000;
-
-                    if (blocksPersisted++ < blocksToPersistList.Count - (2 + Math.Max(0, extraBlocks))) continue;
-                    // Empirically calibrated for relaying the most recent 2 blocks persisted with 15s network
-                    // Increase in the rate of 1 block per second in configurations with faster blocks
-
-                    if (blockToPersist.Index + 100 >= header_index.Count)
-                        system.LocalNode.Tell(new LocalNode.RelayDirectly { Inventory = blockToPersist });
+                    system.SyncManager.Tell(new SyncManager.InvalidBlockIndex { InvalidIndex = block.Index });
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs]: Why tell `SyncManager` this message?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: When Blockchain receive a invalid block, we need to tell SyncManager to retrieve the block of that height and increment the error counter of the node sending the invalid block by 1, which helps us later assess the health of the node.

**Comment by cloud8little** [comment]
Smoke Test Passed for single node CN.
Speed Test for Syncing block comparison:

**offline package sync**:
No obevious difference, but with this pr, the offline syncing is a bit slower.

block height | baseline | pr1397
-- | -- | --
10057 | 25.51 | 27.95
20043 | 49.59 | 54.64

**P2P Sync time(seconds) with StatesDumper intalled (start from index 0)**
Improve about 7 times.

block height | baseline | pr1397
-- | -- | --
21130 (start from 0) | 750 | 98.66

**P2P Sync time(seconds) without StatesDumper intalled (start from index 30)**
Improve about 4~5times.

block height | baseline | pr1397
-- | -- | --
21130  | 450 | 95.01
21149  | 510 | 82

will do some functional explore test later and update the result.

File: src/neo/Ledger/Blockchain.cs [hunk 26]
```diff
@@ -294,78 +295,30 @@ private RelayResultReason OnNewBlock(Block block)
...
+                    return RelayResultReason.Invalid;
                 }
+                block_cache_unverified.Remove(block.Index);
+                Persist(block);
+                system.LocalNode.Tell(Message.Create(MessageCommand.Ping, PingPayload.Create(Singleton.Height)));
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs]: `Ping`?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: `Ping` tells the other nodes that I have persisted a new block, so the other lower nodes will ask for the new block.

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: We send new blocks directly to other nodes before this pr.

**Comment by Tommo-L** [comment]
Could we review this PR. We want to add node health and security mechanism,

File: src/neo/Ledger/Blockchain.cs (hunk 25 above)
Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: Wait for #1495

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: Please listen to the event stream.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: https://github.com/neo-project/neo/blob/4755824fece8c577874910fd69702e38ed777193/src/neo/Ledger/Blockchain.cs#L29

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: OK. I will modify it.

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: @erikzhang Done.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: Then `SyncManager.InvalidBlockIndex` is no more needed.

File: src/neo/Ledger/Blockchain.cs [hunk 27]
```diff
@@ -311,78 +312,25 @@ private VerifyResult OnNewBlock(Block block)
...
-
-                    // 15000 is the default among of seconds per block, while MilliSecondsPerBlock is the current
-                    uint extraBlocks = (15000 - MillisecondsPerBlock) / 1000;
-
-                    if (blocksPersisted++ < blocksToPersistList.Count - (2 + Math.Max(0, extraBlocks))) continue;
-                    // Empirically calibrated for relaying the most recent 2 blocks persisted with 15s network
-                    // Increase in the rate of 1 block per second in configurations with faster blocks
-
-                    if (blockToPersist.Index + 100 >= header_index.Count)
-                        system.LocalNode.Tell(new LocalNode.RelayDirectly { Inventory = blockToPersist });
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs]: I think this should not be removed. What do you think?

Comment (Tommo-L) [reply src/neo/Ledger/Blockchain.cs]: For me, I think we should remove. Since we already have `SysncManager`, it's better for us to move all the synchronization logic into it.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: Once you received a block, you must relay it to the other nodes. Otherwise the network doesn't work.

Comment (Tommo-L) [reply src/neo/Ledger/Blockchain.cs]: That's right, maybe we should move L359 here?

```c#
system.LocalNode.Tell(Message.Create(MessageCommand.Ping, PingPayload.Create(Singleton.Height + 1)));
```

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: @Tommo-L You are right.

File: src/neo/Ledger/Blockchain.cs [hunk 28]
```diff
@@ -442,9 +369,6 @@ protected override void OnReceive(object message)
                 case FillMemoryPool fill:
                     OnFillMemoryPool(fill.Transactions);
                     break;
-                case Header[] headers:
-                    OnNewHeaders(headers);
-                    break;
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs]: If we received headers, we just ignore them? I don't think it's a good idea. Why not we retain the old logic?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: In the old logic, we will save the headers. But I think it's useless.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: Maybe we can make it compatible to get blocks by both index and hash?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: We retain the `MessageCommand. GetBlocks`,  other nodes could use it to get blocks by hash.

File: src/neo/Network/P2P/Payloads/GetHeadersPayload.cs [hunk 29]
```diff
@@ -0,0 +1,37 @@
+using Neo.IO;
+using System;
+using System.IO;
+
+namespace Neo.Network.P2P.Payloads
+{
+    public class GetHeadersPayload : ISerializable
```
Comment (erikzhang) [inline src/neo/Network/P2P/Payloads/GetHeadersPayload.cs]: I think this is the same as `GetBlockDataPayload`. Maybe we can use only one payload. It can be renamed to `GetBlockByIndexPayload`.

Comment (ShawnYun) [reply src/neo/Network/P2P/Payloads/GetHeadersPayload.cs]: Yes. Renaming it will make it easier to understand.

Comment (ShawnYun) [reply src/neo/Network/P2P/Payloads/GetHeadersPayload.cs]: Done

File: src/neo/Network/P2P/Payloads/GetBlockByIndexPayload.cs [hunk 30]
```diff
@@ -4,17 +4,17 @@
 
 namespace Neo.Network.P2P.Payloads
 {
-    public class GetBlockDataPayload : ISerializable
+    public class GetBlockByIndexPayload : ISerializable
     {
-        private const ushort MaxBlocksCount = 500;
+        private const ushort MaxBlocksCount = 2000;
```
Comment (erikzhang) [inline src/neo/Network/P2P/Payloads/GetBlockByIndexPayload.cs]: This should be `500`.

File: src/neo/Network/P2P/ProtocolHandler.cs [hunk 31]
```diff
@@ -141,13 +138,20 @@ private void OnMessage(Message msg)
...
                 case MessageCommand.MerkleBlock:
                 case MessageCommand.NotFound:
                 case MessageCommand.Reject:
                 default: break;
             }
         }
 
+        private void OnBlockReceived(Block payload)
+        {
+            if (payload != null)
```
Comment (erikzhang) [inline src/neo/Network/P2P/ProtocolHandler.cs]: The payload can't be `null`.

File: src/neo/Network/P2P/ProtocolHandler.cs [hunk 32]
```diff
@@ -89,7 +89,7 @@ private void OnMessage(Message msg)
                     OnAddrMessageReceived((AddrPayload)msg.Payload);
                     break;
                 case MessageCommand.Block:
-                    OnInventoryReceived((Block)msg.Payload);
+                    OnBlockReceived((Block)msg.Payload);
```
Comment (erikzhang) [inline src/neo/Network/P2P/ProtocolHandler.cs]: I think it should be handled in `OnInventoryReceived()`.

Comment (ShawnYun) [reply src/neo/Network/P2P/ProtocolHandler.cs]: Done

**Comment by erikzhang** [comment]
Please consider the changes in #1548.

**Comment by ShawnYun** [comment]
@erikzhang Has deleted `subscribe`.

File: src/neo/Network/P2P/SyncManager.cs [hunk 33]
```diff
@@ -33,8 +33,6 @@ public SyncManager(NeoSystem system)
         {
             this.system = system;
             this.lastTaskIndex = Blockchain.Singleton.Height;
-            Context.System.EventStream.Subscribe(Self, typeof(Blockchain.PersistCompleted));
```
Comment (erikzhang) [inline src/neo/Network/P2P/SyncManager.cs]: This shouldn't be removed.

**Comment by erikzhang** [comment]
Can you merge `SyncManager` with `TaskManager`?

File: src/neo/Ledger/Blockchain.cs [hunk 34]
```diff
@@ -62,7 +62,6 @@ public class RelayResult { public IInventory Inventory; public VerifyResult Resu
         private readonly NeoSystem system;
         private readonly List<UInt256> header_index = new List<UInt256>();
         private uint stored_header_count = 0;
-        private readonly Dictionary<UInt256, Block> block_cache = new Dictionary<UInt256, Block>();
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs:65]: Maybe the `block_cache` should be kept? #1592

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs:65]: Yes, I kept it and test now.

File: src/neo/Ledger/Blockchain.cs [hunk 35]
```diff
@@ -62,7 +62,7 @@ public class RelayResult { public IInventory Inventory; public VerifyResult Resu
...
+        private readonly Dictionary<uint, Block> block_cache = new Dictionary<uint, Block>();
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs:65]: If it is `Dictionary<UInt256, Block>`, then we can use the cache for both overloads of `GetBlock()`.

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: Done.

File: src/neo/Ledger/Blockchain.cs [hunk 36]
```diff
@@ -197,6 +197,9 @@ public Block GetBlock(UInt256 hash)
 
         public UInt256 GetBlockHash(uint index)
         {
+            var kvp = block_cache.FirstOrDefault(kvp => kvp.Value.Index == index);
+            if (kvp.Key != null)
+                return kvp.Value.Hash;
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs:202]: Why?

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs:202]: We should get the hash from block_cache first. Otherwise you cannot get block in block_cache by Index.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs:202]: Why? The hash in `block_cache` must also be in `header_index`. Because the `block_cache` stores all the blocks that have been persisted.

Comment (Tommo-L) [reply src/neo/Ledger/Blockchain.cs:202]: >  the block_cache stores all the blocks that have been persisted.

No, `block_cache` will also store the block to be persisted, which is not contained in `header_index`.

https://github.com/neo-project/neo/blob/a995e029f3b59b0d350181e855390009ed240c55/src/neo/Ledger/Blockchain.cs#L333-L335

File: src/neo/Ledger/Blockchain.cs [hunk 37]
```diff
@@ -314,78 +324,27 @@ private VerifyResult OnNewBlock(Block block)
...
-                    uint extraBlocks = (15000 - MillisecondsPerBlock) / 1000;
-
-                    if (blocksPersisted++ < blocksToPersistList.Count - (2 + Math.Max(0, extraBlocks))) continue;
-                    // Empirically calibrated for relaying the most recent 2 blocks persisted with 15s network
-                    // Increase in the rate of 1 block per second in configurations with faster blocks
-
-                    if (blockToPersist.Index + 100 >= header_index.Count)
-                        system.LocalNode.Tell(new LocalNode.RelayDirectly { Inventory = blockToPersist });
-                }
+                block_cache.TryAdd(block.Hash, block);
```
Comment (Tommo-L) [inline src/neo/Ledger/Blockchain.cs:336]: Here, `block_cache` will store the block to be persisted.

File: src/neo/Ledger/Blockchain.cs (hunk 36 above)
Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs:201]: `Dictionary` is not thread-safe, you may modify it while traversing the `block_cache`. I think we should delete this paragraph directly.

File: src/neo/Ledger/Blockchain.cs (hunk 37 above)
Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs:335]: But the block will be added soon.

Comment (Tommo-L) [reply src/neo/Ledger/Blockchain.cs:335]: If we don't store here, this will cause our synchronization to slow down, as the other nodes must wait for it to persist. 
Or store the `header_index` here, too?

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs:335]: Yes. We can update `header_index` at the beginning of `Persist()`.

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs:332]: Have modified.

File: src/neo/Ledger/Blockchain.cs [hunk 38]
```diff
@@ -313,78 +320,29 @@ private VerifyResult OnNewBlock(Block block)
...
+                block_cache_unverified.Remove(block.Index);
+                if (block.Index == header_index.Count)
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs:334]: Is this necessary? I think it has been verified in L328.

File: src/neo/Ledger/Blockchain.cs [hunk 39]
```diff
@@ -516,6 +450,8 @@ private void Persist(Block block)
                     header_index.Add(block.Hash);
```
Comment (erikzhang) [inline src/neo/Ledger/Blockchain.cs:450]: This should be removed.

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs:450]: In `Persist(GenesisBlock);` and `OnImport`, we need it.

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs:450]: Then move it to the beginning of `Persist()`, and remove it from L334.

Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs]: done and tested.

File: src/neo/Ledger/Blockchain.cs [hunk 40]
```diff
@@ -313,78 +320,27 @@ private VerifyResult OnNewBlock(Block block)
...
-                    if (blocksPersisted++ < blocksToPersistList.Count - (2 + Math.Max(0, extraBlocks))) continue;
-                    // Empirically calibrated for relaying the most recent 2 blocks persisted with 15s network
-                    // Increase in the rate of 1 block per second in configurations with faster blocks
-
-                    if (blockToPersist.Index + 100 >= header_index.Count)
-                        system.LocalNode.Tell(new LocalNode.RelayDirectly { Inventory = blockToPersist });
-                }
+                block_cache.TryAdd(block.Hash, block);
+                block_cache_unverified.Remove(block.Index);
+                system.LocalNode.Tell(Message.Create(MessageCommand.Ping, PingPayload.Create(Singleton.Height + 1)));
```
Comment (shargon) [inline src/neo/Ledger/Blockchain.cs:334]: After persist and Height without +1 ?

File: tests/neo.UnitTests/Network/P2P/UT_TaskManagerMailbox.cs [hunk 41]
```diff
@@ -41,8 +41,7 @@ public void TaskManager_Test_IsHighPriority()
             uut.IsHighPriority(new TaskManager.NewTasks { Payload = new InvPayload() }).Should().Be(false);
 
             // high priority
-            // -> NewTasks: payload Block or Consensus
-            uut.IsHighPriority(new TaskManager.NewTasks { Payload = new InvPayload { Type = InventoryType.Block } }).Should().Be(true);
```
Comment (shargon) [inline tests/neo.UnitTests/Network/P2P/UT_TaskManagerMailbox.cs:45]: Why this UT it's removed?

**Comment by erikzhang** [comment]
I have minimized the changes and it should be easier to review now. Requires retesting and review by others.

**Comment by shargon** [comment]
Does we need `HeadersPayload` or it's for light nodes?

File: src/neo/Ledger/Blockchain.cs (hunk 40 above)
Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs:334]: Persist is slow, so we can store the block in block_cache and tell the new height to other node before persist.

**Comment by ShawnYun** [comment]
I think we should keep it for light nodes or other nodes that need to get the block header

File: src/neo/Network/P2P/TaskManager.cs [hunk 42]
```diff
@@ -191,22 +221,38 @@ private void OnTerminated(IActorRef actor)
...
                     {
-                        if (session.Tasks.Remove(task.Key))
+                        if (session.InvTasks.Remove(task.Key))
                             DecrementGlobalTask(task.Key);
                     }
-            foreach (TaskSession session in sessions.Values)
-                RequestTasks(session);
+                }
+
+                foreach (KeyValuePair<uint, DateTime> kvp in session.IndexTasks)
```
Comment (Tommo-L) [inline src/neo/Network/P2P/TaskManager.cs:245]: Put block synchronization before inv task?

File: src/neo/Network/P2P/TaskSession.cs [hunk 43]
```diff
@@ -1,31 +1,23 @@
...
-        public bool HasTask => Tasks.Count > 0;
-        public uint StartHeight { get; }
-        public uint LastBlockIndex { get; set; }
+        public uint TimeoutTimes = 0;
+        public uint InvalidBlockCount = 0;
+        public uint LastBlockIndex = 0;
 
-        public TaskSession(IActorRef node, VersionPayload version)
+        public bool HasInvTask => InvTasks.Count > 0;
+        public bool HasIndexTask => IndexTasks.Count > 0;
```
Comment (Tommo-L) [inline src/neo/Network/P2P/TaskSession.cs:16]: We never use the two variables?

**Comment by Tommo-L** [comment]
> Does we need `HeadersPayload` or it's for light nodes?

The cross-chain relayer need to sync block header.

File: src/neo/Network/P2P/TaskManager.cs [hunk 44]
```diff
@@ -288,11 +318,10 @@ internal protected override bool IsHighPriority(object message)
             switch (message)
             {
                 case TaskManager.Register _:
-                case TaskManager.Update _:
                 case TaskManager.RestartTasks _:
                     return true;
                 case TaskManager.NewTasks tasks:
-                    if (tasks.Payload.Type == InventoryType.Block || tasks.Payload.Type == InventoryType.Consensus)
+                    if (tasks.Payload.Type == InventoryType.Consensus)
```
Comment (Tommo-L) [inline src/neo/Network/P2P/TaskManager.cs:324]: Reset `InventoryType.Block`?

File: src/neo/Network/P2P/TaskSession.cs (hunk 43 above)
Comment (ShawnYun) [reply src/neo/Network/P2P/TaskSession.cs:16]: Yes

Comment (erikzhang) [reply src/neo/Network/P2P/TaskSession.cs:16]: Then they should be removed.

File: src/neo/Ledger/Blockchain.cs (hunk 40 above)
Comment (vncoelho) [inline src/neo/Ledger/Blockchain.cs:334]: @ShawnYun, could add a comment above this line `system.LocalNode.Tell(Message.Create(MessageCommand.Ping, PingPayload.Create(Singleton.Height + 1)));`
Sometimes I forget if this is telling the node itself or notifying its peers.
Perhaps it is good to have a brief comment before it.

File: src/neo/Network/P2P/TaskManager.cs [hunk 45]
```diff
@@ -220,58 +266,42 @@ public static Props Props(NeoSystem system)
...
 
-        private void RequestTasks(TaskSession session)
+        private void RequestTasks()
         {
-            if (session.HasTask) return;
-            // If there are pending tasks of InventoryType.Block we should process them
-            if (session.AvailableTasks.Count > 0)
+            if (sessions.Count() == 0) return;
+
+            SendPingMessage();
```
Comment (vncoelho) [inline src/neo/Network/P2P/TaskManager.cs:273]: Well organized.

File: src/neo/Network/P2P/TaskManager.cs [hunk 46]
```diff
@@ -14,105 +14,140 @@ namespace Neo.Network.P2P
...
+                .OrderBy(p => p.Value.IndexTasks.Count)
+                .ThenBy(s => rand.Next())
+                .FirstOrDefault();
+            if (remoteNode.Value == null)
+            {
+                failedSyncTasks.Add(index);
+                return false;
+            }
+            TaskSession session = remoteNode.Value;
+            session.IndexTasks.Add(index, TimeProvider.Current.UtcNow);
```
Comment (vncoelho) [inline src/neo/Network/P2P/TaskManager.cs:65]: What happens to the local variable `session` here?

File: src/neo/Network/P2P/TaskManager.cs [hunk 47]
```diff
@@ -220,58 +266,42 @@ public static Props Props(NeoSystem system)
...
-            // If not HeaderTask pending to be processed it should ask for more Blocks
-            if ((!HasHeaderTask || globalTasks[HeaderTaskHash] < MaxConncurrentTasks) && Blockchain.Singleton.HeaderHeight < session.LastBlockIndex)
+            int taskCounts = sessions.Values.Sum(p => p.IndexTasks.Count);
+            var highestBlockIndex = sessions.Values.Max(p => p.LastBlockIndex);
+            for (; taskCounts < MaxSyncTasksCount; taskCounts++)
             {
-                session.Tasks[HeaderTaskHash] = DateTime.UtcNow;
-                IncrementGlobalTask(HeaderTaskHash);
-                session.RemoteNode.Tell(Message.Create(MessageCommand.GetHeaders, GetBlocksPayload.Create(Blockchain.Singleton.CurrentHeaderHash)));
+                if (lastTaskIndex >= highestBlockIndex) break;
```
Comment (vncoelho) [inline src/neo/Network/P2P/TaskManager.cs:289]: Very good, I believe nodes are going to behave nice after this change.

File: src/neo/Network/P2P/TaskManager.cs [hunk 48]
```diff
@@ -14,105 +14,140 @@ namespace Neo.Network.P2P
...
+            var session = sessions.Values.FirstOrDefault(p => p.IndexTasks.ContainsKey(block.Index));
+            if (session is null) return;
+            session.IndexTasks.Remove(block.Index);
+            receivedBlockIndex.Add(block.Index, session);
+            RequestTasks();
+        }
+
+        private void OnInvalidBlock(Block invalidBlock)
+        {
+            receivedBlockIndex.TryGetValue(invalidBlock.Index, out TaskSession session);
```
Comment (vncoelho) [inline src/neo/Network/P2P/TaskManager.cs:82]: Perhaps we could run a loop and exclude all sessions that could had sent this `OnInvalidBlock`.

File: src/neo/Ledger/Blockchain.cs (hunk 40 above)
Comment (ShawnYun) [reply src/neo/Ledger/Blockchain.cs:334]: I will add it

File: src/neo/Network/P2P/TaskManager.cs (hunk 46 above)
Comment (ShawnYun) [reply src/neo/Network/P2P/TaskManager.cs:65]: It records the time that the task is assigned so that it can detect whether the task has timed out in the timer.

File: src/neo/Network/P2P/TaskManager.cs (hunk 48 above)
Comment (ShawnYun) [reply src/neo/Network/P2P/TaskManager.cs:82]: Good idea, I think we can add it in 'node health', after this PR.

**Comment by ixje** [comment]
👏

**Comment by shargon** [comment]
Please, give me a couple of days for review it

**Comment by erikzhang** [comment]
@shargon Are you still reviewing it?

**Comment by cloud8little** [comment]
Test Environment: 1 Consensus, 1 normal node, on the same physical machine
| Index or Hash | neo| neo-vm| neo-node| neo-devpack-dotnet | 
| ------------ | -------- | ------ | -------- | ------ |
| byIndex | Commit: b5cc115 | https://github.com/neo-project/neo-vm/commit/57519e2e25bc39c944f8e691d16e8a257770c82e | https://github.com/neo-project/neo-node/commit/d103bc58cc9b62fc71ba7ea08865236b132fd9aa | db88ae768903fd73ccba701b2c6bae3d4bfc773f |
| byHash | https://github.com/neo-project/neo/commit/1451f849d98915775f794684a9dd073cececa6d0 | https://github.com/neo-project/neo-vm/commit/57519e2e25bc39c944f8e691d16e8a257770c82e | https://github.com/neo-project/neo-node/commit/d103bc58cc9b62fc71ba7ea08865236b132fd9aa | db88ae768903fd73ccba701b2c6bae3d4bfc773f |

1. Note: this PR is incompatible with get block by block hash, so the consensus node should be consistent.
2. Functional smoke test passed. include:
- send neo/gas 
- deploy nep5 contract
- invoke nep5 contract method, totalSupply/name/transfer/balanceOf
- send bulk transaction which leads to maximum number of tx, 512.
3. Speed comparison
time(seconds) without StatesDumper installed; without transactions. Baseline is get blocks in the old way, the speed of this PR is 11 times of the baseline.

| block height | baseline | pr1397 |
| ------------ | -------- | ------ |
| 2030         | 91       | 8.02   |

2 blocks with 512 transactions, under this situation, get blocks of baseline is even slower, while the speed of block index is nearly the same with no transactions.

| block height | baseline | pr1397 |
| ------------ | -------- | ------ |
| 2428         | 120 | 8.68 |

with StatesDumper installed, BlockCacheSize=1, not much difference with/without StatesDumper installed.

| block height | baseline | pr1397 |
| ------------ | -------- | ------ |
| 2428         | 121 | 10 |

**Comment by vncoelho** [comment]
@ShawnYun, could you check the conflicts?
We are using this branch on our experiments already and it would be good to update this asap in order to find any possible error.

**Comment by ShawnYun** [comment]
@vncoelho Resolved.

File: src/neo/Network/P2P/RemoteNode.ProtocolHandler.cs [hunk 49]
```diff
@@ -82,17 +82,14 @@ private void OnMessage(Message msg)
...
+                case MessageCommand.GetBlockByIndex:
+                    OnGetBlockByIndexMessageReceived((GetBlockByIndexPayload)msg.Payload);
                     break;
                 case MessageCommand.GetData:
                     OnGetDataMessageReceived((InvPayload)msg.Payload);
                     break;
                 case MessageCommand.GetHeaders:
-                    OnGetHeadersMessageReceived((GetBlocksPayload)msg.Payload);
-                    break;
-                case MessageCommand.Headers:
```
[the remark this answers is not in the document]
Comment (Tommo-L) [reply src/neo/Network/P2P/RemoteNode.ProtocolHandler.cs:94]: We need to support `GetHeaders` for SPV or other light nodes. 
`Headers` is not used between full nodes, as they don't need to sync them.

File: src/neo/Network/P2P/TaskManager.cs [hunk 50]
```diff
@@ -18,6 +18,7 @@ public class Register { public VersionPayload Version; }
         public class Update { public uint LastBlockIndex; }
         public class NewTasks { public InvPayload Payload; }
         public class RestartTasks { public InvPayload Payload; }
+        private class Counter { public int Value; }
```
Comment (erikzhang) [inline src/neo/Network/P2P/TaskManager.cs:21]: Use `Tuple<T>`? But I think this optimization is of little significance.

Comment (shargon) [reply src/neo/Network/P2P/TaskManager.cs:21]: Tupple is immutable

File: src/neo/Network/P2P/TaskManager.cs [hunk 51]
```diff
@@ -17,81 +17,110 @@ internal class TaskManager : UntypedActor
...
+        private readonly NeoSystem system;
         /// <summary>
         /// A set of known hashes, of inventories or payloads, already received.
-        /// </summary>        
+        /// </summary>
         private readonly HashSetCache<UInt256> knownHashes;
-        private readonly Dictionary<UInt256, int> globalTasks = new Dictionary<UInt256, int>();
+        private readonly Dictionary<UInt256, Counter> globalTasks = new Dictionary<UInt256, Counter>();
+        private readonly Dictionary<uint, TaskSession> receivedBlockIndex = new Dictionary<uint, TaskSession>();
+        private readonly List<uint> failedSyncTasks = new List<uint>();
```
Comment (shargon) [inline src/neo/Network/P2P/TaskManager.cs:39]: `HashSet<uint> failedSyncTasks = new HashSet<uint>();` ?

File: src/neo/Network/P2P/TaskManager.cs [hunk 52]
```diff
@@ -17,81 +17,110 @@ internal class TaskManager : UntypedActor
...
+            failedSyncTasks.Remove(index);
+            return true;
+        }
+
+        private void OnBlock(Block block)
+        {
+            var session = sessions.Values.FirstOrDefault(p => p.IndexTasks.ContainsKey(block.Index));
+            if (session is null) return;
+            session.IndexTasks.Remove(block.Index);
+            receivedBlockIndex.Add(block.Index, session);
```
Comment (shargon) [inline src/neo/Network/P2P/TaskManager.cs:78]: TryAdd or receivedBlockIndex[block.Index] = ?

File: src/neo/Network/P2P/TaskManager.cs (hunk 50 above)
Comment (erikzhang) [reply src/neo/Network/P2P/TaskManager.cs:21]: But this is weird. Can we just use `Dictionary<UInt256, int>`?

Comment (shargon) [reply src/neo/Network/P2P/TaskManager.cs:21]: The problem with uint as value if that for change the value we need to search again in the dictionary

Comment (erikzhang) [reply src/neo/Network/P2P/TaskManager.cs:21]: If the key does not exist in the dictionary, you will have to create a new object (`Counter`), which is most of the time. So it is hard to say whether there is a performance improvement. And even if there is an improvement, I don't expect much improvement. And this reduces the code readability.

Comment (erikzhang) [reply src/neo/Network/P2P/TaskManager.cs:21]: So do you mind changing it back? @shargon
