### PR TITLE
Fix memory leak as transactions are continuously received.

### LINKED ISSUE #509: Limit KnownHashes size
Currently, it looks like that the ` HashSet<UInt256> knownHashes` has no size limit.
https://github.com/neo-project/neo/blob/7883e587a9448330d21669ebe748402871da3a50/neo/Network/P2P/TaskManager.cs#L27

In my local experiment it quickly reaches huge sizes.
Maybe it can reach something around 1M+ in MainNet operation.
Is it a problem to the client or it is expected to handle it in a smooth manner?

If we decide to limit it, which kind of representation do you recommend?

### PR DESCRIPTION
**Pull request by yongjiema**
Closes #509

### CODE REVIEW

File: neo/Network/P2P/ProtocolHandler.cs [hunk 1]
```diff
@@ -21,9 +22,32 @@ public class SetVersion { public VersionPayload Version; }
...
+
+                this.maxCapacity = maxCapacity;
+                this.orderedDictionary = new OrderedDictionary(maxCapacity);
+            }
+
+            public bool Add(T item)
+            {
+                if (orderedDictionary.Contains(item)) return false;
+                if (orderedDictionary.Count >= maxCapacity)
+                    orderedDictionary.RemoveAt(0);
```
Comment (vncoelho) [inline neo/Network/P2P/ProtocolHandler.cs]: FIFO, right?

File: neo/Network/P2P/ProtocolHandler.cs [hunk 2]
```diff
@@ -21,9 +22,32 @@ public class SetVersion { public VersionPayload Version; }
         public class SetVerack { }
         public class SetFilter { public BloomFilter Filter; }
 
+        private class LimitedSet<T>
+        {
+            private int maxCapacity;
+            private OrderedDictionary orderedDictionary;
```
Comment (jsolman) [inline neo/Network/P2P/ProtocolHandler.cs]: This should use something like an LRU cache.

File: neo/Network/P2P/ProtocolHandler.cs [hunk 3]
```diff
@@ -21,9 +22,32 @@ public class SetVersion { public VersionPayload Version; }
...
+
+            public LimitedSet(int maxCapacity = 100)
```
Comment (vncoelho) [inline neo/Network/P2P/ProtocolHandler.cs]: How did you reach 100?
Do you think it is enough?

I had thought about a bigger value.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 1 above)
Comment (jsolman) [inline neo/Network/P2P/ProtocolHandler.cs]: It would be better if it batch removed when above a threshold instead of needing to remove every time once at capacity. Also, it would be best to remove the least recently used item.

File: neo/Network/P2P/ProtocolHandler.cs [hunk 4]
```diff
@@ -21,9 +22,32 @@ public class SetVersion { public VersionPayload Version; }
...
+                this.maxCapacity = maxCapacity;
+                this.orderedDictionary = new OrderedDictionary(maxCapacity);
+            }
+
+            public bool Add(T item)
+            {
+                if (orderedDictionary.Contains(item)) return false;
+                if (orderedDictionary.Count >= maxCapacity)
+                    orderedDictionary.RemoveAt(0);
+                orderedDictionary.Add(item, null);
```
Comment (jsolman) [inline neo/Network/P2P/ProtocolHandler.cs]: Since you are adding null as the value, you could just be using a sorted structure that doesn’t have a value like `SortedSet`. However as mentioned above it should really use a structure that evicts least recently accessed items.

Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: Actually sortedset doesn’t help removing in an order so I’ll retract this comment.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 3 above)
Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: I agree with @vncoelho it should hold much more. Maybe like 32K values.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 2 above)
Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: Actually, I guess FIFO is probably fine for this use. Going to resolve this also.

File: neo/Network/P2P/ProtocolHandler.cs [hunk 5]
```diff
@@ -21,9 +22,32 @@ public class SetVersion { public VersionPayload Version; }
         public class SetVerack { }
         public class SetFilter { public BloomFilter Filter; }
 
+        private class LimitedSet<T>
```
Comment (jsolman) [inline neo/Network/P2P/ProtocolHandler.cs]: Please move this data structure to its own file. It may be usedful other places as well.

Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: Also maybe rename to `LimitedFIFOSet`

File: neo/Network/P2P/ProtocolHandler.cs (hunk 1 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: Yes, but the existing FIFO cache (https://github.com/neo-project/neo/blob/master/neo/IO/Caching/FIFOCache.cs) is key-value based.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 3 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: It's OK for me as it just lookup most recently hashes, but can increase to a larger size.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 1 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: Batch remove would possible introduce memory leak again for me.

Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: Batch remove shouldn’t introduce a memory leak; suppose it batch removed 1/8 of capacity when it reached capacity. Why do you believe it would introduce a memory leak?

File: neo/Network/P2P/ProtocolHandler.cs (hunk 3 above)
Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: With such a small size it can defeat its purpose of preventing processing duplicates,  since the cache is easily exhausted with high incoming volume.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 1 above)
Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: I think @vncoelho was just asking to clarify that your implementation here is FIFO. And it is so, I think we can resolve this comment.

I agree that you shouldn’t use the existing implementation of the `FIFOCache` class since it has locking that you don’t need here, plus what it does for removing when at capacity is not optimal as it sorts each time to remove the oldest (and it doesn’t use a data structure that keeps the items sorted). Its approach wouldn’t be so bad if it used batch removal. We should actually improve the `Cache` class implementation also for how it handles the at capacity situation.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 3 above)
Comment (vncoelho) [reply neo/Network/P2P/ProtocolHandler.cs]: I just remember that it use to grow very quick.

But 100 looks small because maybe we are requesting many blocks and etc... I am not sure.
Some tests would be good for setting this nicely.

Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: 👍

File: neo/Network/P2P/ProtocolHandler.cs (hunk 1 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: It would be fine as you said, but it may need a larger size.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 5 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: 👍

Comment (shargon) [reply neo/Network/P2P/ProtocolHandler.cs]: without inheritance?

File: neo/Network/P2P/ProtocolHandler.cs (hunk 3 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: > I just remember that it use to grow very quick.
> 
> But 100 looks small because maybe we are requesting many blocks and etc... I am not sure.
> Some tests would be good for setting this nicely.

I made the size configurable, you can change it later after some tests.

Comment (erikzhang) [reply neo/Network/P2P/ProtocolHandler.cs]: I think we can find a best value and make it fixed.

Comment (vncoelho) [reply neo/Network/P2P/ProtocolHandler.cs]: Very pro-active @yongjiema, thanks for this configuration.

It will help during tests.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 5 above)
Comment (jsolman) [reply neo/Network/P2P/ProtocolHandler.cs]: @shargon I think using composition is fine here rather than inheritance; however, it would probably be the best practice to have interface(s) it implements for its operations.

**Comment by shargon** [comment]
Dictionary is not needed, i changed it to a simple List, we save more memory

**Comment by jsolman** [comment]
@shargon I disagree with your change to a list. Lookup is slow which is what is normally being done, and we want to hold 32K or more items.

**Comment by shargon** [comment]
`Contains` method is the same in a List and a Dictionary, we can use a `SortedList` or made some benchmarks, but one `Dictionary` require a `Key` and a `Value`, `null` as value is weird, is a waste of memory and resources ...

**Comment by shargon** [comment]
`SortedList` is based on a `Dictionary` too :(, we should create our SortedList if we want to improve the performance

**Comment by vncoelho** [comment]
This PR closes #509.

Let's do the Bloom Filter...kkkkkkkkkkkkk
I am joking. Let's go in the current direction.

**Comment by shargon** [comment]
@jsolman what do you think like this

```csharp
using System;
using System.Linq;
using System.Collections.Generic;

namespace Neo.IO.Caching
{
    internal class FIFOSet<T> where T : IEquatable<T>
    {
        private int maxCapacity;
        private int removeCount;
        private SortedSet<T> orderedList;

        public FIFOSet(int maxCapacity, decimal? batchSize = 0.1m)
        {
            if (maxCapacity <= 0) throw new ArgumentOutOfRangeException(nameof(maxCapacity));
            if (batchSize <= 0) throw new ArgumentOutOfRangeException(nameof(batchSize));

            this.maxCapacity = maxCapacity;
            this.removeCount = batchSize != null ? (int)(batchSize <= 1.0m ? maxCapacity * batchSize : maxCapacity) : 1;
            this.orderedList = new SortedSet<T>();
        }

        public bool Add(T item)
        {
            if (orderedList.Contains(item)) return false;
            if (orderedList.Count >= maxCapacity)
            {
                if (removeCount == maxCapacity)
                {
                    orderedList.Clear();
                }
                else
                {
                    for (int i = 0; i < removeCount; i++)
                        orderedList.Remove(orderedList.First());
                }
            }
            orderedList.Add(item);
            return true;
        }
    }
}
```

**Comment by jsolman** [comment]
@shargon a hashset thst has linked list in the nodes is fastest and best.

**Comment by yongjiema** [comment]
> `Contains` method is the same in a List and a Dictionary, we can use a `SortedList` or made some benchmarks, but one `Dictionary` require a `Key` and a `Value`, `null` as value is weird, is a waste of memory and resources ...

From the [document](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary.contains?view=netframework-4.7.2#System_Collections_Specialized_OrderedDictionary_Contains_System_Object_) and the source code, I can see it lookup from hashtable, that's why I chosen it.

**Comment by jsolman** [comment]
@yongjiema I think you made a reasonable choice

**Comment by jsolman** [comment]
IMO memory savings is trivial and we can just revert this: https://github.com/neo-project/neo/commit/27bf008c029ae1ca1a93c3b1af7f12f15636819d

**Comment by shargon** [comment]
I will make some benchmarks

**Comment by shargon** [comment]
According to my tests, we should use a HashSet

```
BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17134.648 (1803/April2018Update/Redstone4)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
Frequency=2531253 Hz, Resolution=395.0613 ns, Timer=TSC
.NET Core SDK=2.2.104
  [Host]     : .NET Core 2.2.2 (CoreCLR 4.6.27317.07, CoreFX 4.6.27318.02), 64bit RyuJIT
  DefaultJob : .NET Core 2.2.2 (CoreCLR 4.6.27317.07, CoreFX 4.6.27318.02), 64bit RyuJIT


            Method |         Mean |        Error |       StdDev |
------------------ |-------------:|-------------:|-------------:|
         SortedSet |     855.6 ms |    10.556 ms |     9.874 ms |
              List | 165,354.0 ms | 3,204.526 ms | 2,997.516 ms |
 OrderedDictionary |     295.0 ms |     3.159 ms |     2.638 ms |
           HashSet |     119.6 ms |     2.350 ms |     3.517 ms |
```

File: neo/Settings.cs [hunk 6]
```diff
@@ -33,6 +34,7 @@ private ProtocolSettings(IConfigurationSection section)
             this.SystemFee = section.GetSection("SystemFee").GetChildren().ToDictionary(p => (TransactionType)Enum.Parse(typeof(TransactionType), p.Key, true), p => Fixed8.Parse(p.Value));
             this.SecondsPerBlock = GetValueOrDefault(section.GetSection("SecondsPerBlock"), 15u, p => uint.Parse(p));
             this.LowPriorityThreshold = GetValueOrDefault(section.GetSection("LowPriorityThreshold"), Fixed8.FromDecimal(0.001m), p => Fixed8.Parse(p));
+            this.HashCacheSize = GetValueOrDefault(section.GetSection("HashCacheSize"), 100, Int32.Parse);
```
Comment (shargon) [inline neo/Settings.cs]: very low 100?

**Comment by jsolman** [comment]
@shargon you cannot use only a hash set. You will not have fifo behavior with hashset on its own. You would have to benchmark hashset with list nodes in the values and handling the links (which is basicallt what OrderedDictionary is doing). The fact that ordered dictionaries holds references to values is likely not going to slow it down much so writing our own data structure will just save a small amount of memory.

**Comment by jsolman** [comment]
One thing to note though if we do write our own data structure that uses a hashset in combination with linked list nodes, we could use a circular singly linked list, since we only need the fifo behavior, which will be even a little more space efficient than the `OrderedDictionary` that will uses a doubly linked list internally.

**Comment by shargon** [comment]
I understand you ... then i will revert it to use `OrderedDictionary` but in the future we should use other methods because this one use more memory.

**Comment by shargon** [comment]
Open idea: 
- we can merge `knowhashes` and `senthashes`, and use the dictionary value as a flag, for: is sent? or don't

What do you think ? @igormcoelho @jsolman @vncoelho @erikzhang

**Comment by vncoelho** [comment]
I am in favor of that, @shargon, in terms of simplicity.
In terms of efficiency I do not know. @igormcoelho teaches this and can surely help in the discussion. :dancer:

**Comment by igormcoelho** [comment]
Fully agree for unification @shargon. On C++, a bool is equivalent in size to an enum (both are 4B ints). So, size increse wouldn't be an issue, and the huge gain in avoiding repeated keys would be overwelming. The bigger the intersection on groups, the bigger the gains are.

**Comment by erikzhang** [comment]
Usually we will not send back the data sent to us by the other party. So there is almost no intersection between `knowhashes` and `senthashes`.

**Comment by igormcoelho** [comment]
> So there is almost no intersection between knowhashes and senthashes.

@shargon abort plan :laughing:

File: neo/IO/Caching/FIFOSet.cs [hunk 7]
```diff
@@ -0,0 +1,41 @@
+﻿using System;
+using System.Collections.Specialized;
+
+namespace Neo.IO.Caching
+{
+    internal class FIFOSet<T> where T : IEquatable<T>, IComparable<T>
```
Comment (jsolman) [inline neo/IO/Caching/FIFOSet.cs]: Items in a FIFOSet do not need to implement comparable.

File: neo/Settings.cs (hunk 6 above)
Comment (jsolman) [reply neo/Settings.cs]: How about switch to 32 * 1024

File: neo/Settings.cs [hunk 8]
```diff
@@ -15,6 +15,7 @@ public class ProtocolSettings
         public IReadOnlyDictionary<TransactionType, Fixed8> SystemFee { get; }
         public Fixed8 LowPriorityThreshold { get; }
         public uint SecondsPerBlock { get; }
+        public int HashCacheSize { get; }
```
Comment (erikzhang) [inline neo/Settings.cs]: We don't need Settings. Let's find a best value and make it fixed.

Comment (jsolman) [reply neo/Settings.cs]: In that case let’s try using 2x the size of the memory pool and use that.

**Comment by erikzhang** [comment]
Anyone working on this?

**Comment by shargon** [comment]
If we decide to use 2x the mempool size, i can do it

**Comment by jsolman** [comment]
@shargon go for it

**Comment by shargon** [comment]
@yongjiema , please take a look at https://github.com/yongjiema/neo/pull/1

File: neo/IO/Caching/FIFOSet.cs [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+        private readonly int removeCount;
+        private readonly OrderedDictionary data;
+
+        public FIFOSet(int maxCapacity, decimal? batchSize = 0.1m)
+        {
+            if (maxCapacity <= 0) throw new ArgumentOutOfRangeException(nameof(maxCapacity));
+            if (batchSize <= 0) throw new ArgumentOutOfRangeException(nameof(batchSize));
+
+            this.maxCapacity = maxCapacity;
+            this.removeCount = batchSize != null ? (int)(batchSize <= 1.0m ? maxCapacity * batchSize : maxCapacity) : 1;
```
Comment (erikzhang) [inline neo/IO/Caching/FIFOSet.cs]: I think `null` should be the same as the default value.

**Comment by erikzhang** [comment]
Any update?

File: neo/IO/Caching/FIFOSet.cs (hunk 9 above)
Comment (shargon) [reply neo/IO/Caching/FIFOSet.cs]: Done!
