### PR TITLE
Fix/Improve syncing (3x): Adding ping mechanism to TaskManager for replacing StartHeight and PendingKnownHashes strategy

### LINKED ISSUE #841: consensus node stop sync block.
Consensus node stop sync data, unless restart.
image
After restart.
image

This usually happens when a cn ran for a long term.

### PR DESCRIPTION
**Pull request by yongjiema**
Fix #841

### CODE REVIEW

**Comment by shargon** [comment]
Could you explain the fix?

File: neo/Network/P2P/TaskManager.cs [hunk 1]
```diff
@@ -221,7 +222,11 @@ private void RequestTasks(TaskSession session)
                     return;
                 }
             }
-            if ((!HasHeaderTask || globalTasks[HeaderTaskHash] < MaxConncurrentTasks) && Blockchain.Singleton.HeaderHeight < session.StartHeight)
+            if ((!HasHeaderTask || globalTasks[HeaderTaskHash] < MaxConncurrentTasks)
+                && (Blockchain.Singleton.HeaderHeight < session.StartHeight
```
Comment (shargon) [inline neo/Network/P2P/TaskManager.cs]:
```if ((!HasHeaderTask || globalTasks[HeaderTaskHash] < MaxConncurrentTasks)
                && (Blockchain.Singleton.HeaderHeight < session.StartHeight
                    || (Blockchain.Singleton.HeaderHeight == session.StartHeight
                        && Blockchain.Singleton.HeaderHeight == sessions.Select(x => x.Value.StartHeight).Max()
                        && TimeProvider.Current.UtcNow.ToTimestamp() - 60 >= Blockchain.Singleton.GetBlock(Blockchain.Singleton.CurrentHeaderHash)?.Timestamp)
                        ))
```
?

**Comment by erikzhang** [comment]
Looks good. We need to test it.

File: neo/Network/P2P/TaskManager.cs [hunk 2]
```diff
@@ -266,5 +271,13 @@ internal protected override bool IsHighPriority(object message)
                     return false;
             }
         }
+
+        internal protected override bool ShallDrop(object message, IEnumerable queue)
+        {
+            if (!(message is TaskManager.NewTasks tasks)) return false;
+            // Remove duplicate tasks
+            if (queue.OfType<TaskManager.NewTasks>().Any(x => x.Payload.Type == tasks.Payload.Type && x.Payload.Hashes.SequenceEqual(tasks.Payload.Hashes))) return true;
```
Comment (shargon) [inline neo/Network/P2P/TaskManager.cs]: I think that this is very important

File: neo/Network/P2P/TaskManager.cs (hunk 1 above)
Comment (shargon) [reply neo/Network/P2P/TaskManager.cs]: All the condition

```Blockchain.Singleton.HeaderHeight == session.StartHeight
                        && Blockchain.Singleton.HeaderHeight == sessions.Select(x => x.Value.StartHeight).Max()
                        && TimeProvider.Current.UtcNow.ToTimestamp() - 60 >= Blockchain.Singleton.GetBlock(Blockchain.Singleton.CurrentHeaderHash)?.Timestamp)
``` 

should be inside parentheses, right?

**Comment by yongjiema** [comment]
> Could you explain the fix?

This PR is the fix for #841, there have two main reasons caused the issue happen:

1. Too many duplicate new tasks are queued in the `TaskManagerMailbox` from each session, but the `TaskManager` cannot process the mailbox's messages as fast as it was queued, so the mailbox grow  bigger and bigger, then the sync slower, and stop sync at last

2. Another reason is the current node's header reaches the highest one from the connection sessions,  but it might not be updated for a long time, the fix is try to get the new headers if the current header equals the highest one and is not updated for a while.

**Comment by shargon** [comment]
For the issue 1, is possible to detect what kind of task produce this issue? i like the solution, but maybe we should try to find the sender problem.

File: neo/Network/P2P/TaskManager.cs (hunk 1 above)
Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: Yes, the logic is inside parentheses.

**Comment by yongjiema** [comment]
> For the issue 1, is possible to detect what kind of task produce this issue? i like the solution, but maybe we should try to find the sender problem.

I remember the most duplicate tasks is consensus.

**Comment by KickSeason** [comment]
Can you create a pr to master-2.x. We want to have a test on NEO2.x.

**Comment by yongjiema** [comment]
> Can you create a pr to master-2.x. We want to have a test on NEO2.x.

please check #900

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (shargon) [inline neo/Network/P2P/TaskManager.cs]:
```suggestion
            if (queue.OfType<TaskManager.NewTasks>().AsParallel().Any(x => x.Payload.Type == tasks.Payload.Type && x.Payload.Hashes.SequenceEqual(tasks.Payload.Hashes))) return true;
```
Maybe we could precompute a global hash for invPayloads.

**Comment by igormcoelho** [comment]
Congratulations!! Amazing fix!

**Comment by KickSeason** [comment]
Community with NGD are testing #900.

**Comment by KickSeason** [comment]
I also find that if mailbox is crowding with low priority messages, TaskCompleted event will be blocked too.
This even makes things worse. Hight priority task completed event will be blocked too.

**Comment by yongjiema** [comment]
> I also find that if mailbox is crowding with low priority messages, TaskCompleted event will be blocked too.
> This even makes things worse. Hight priority task completed event will be blocked too.

Yes, my another fix in my local is try to set the `TaskCompleted`, `HederTaskCompleted` and `Timer` as high priority, but from my testing, it's also working file without the change, but it's a potential problem, I removed this part for the fix as I think it's better have something like a system messages category which have a higher priority in queues (e.g. `PriorityMessageQueue`)

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (erikzhang) [inline neo/Network/P2P/TaskManager.cs]: Are these duplicate messages coming from the same node or from different nodes?

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: Different nodes.

Comment (erikzhang) [reply neo/Network/P2P/TaskManager.cs]: Maybe we should limit the number of connections? It looks like a performance issue, not a logic issue.

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: I think that we need to re-run the tests after the last fix, @yongjiema, because the FifoSet had some problems in the ExceptWith command.

But I agree with the last comment I saw from you guys, @KickSeason, about the TaskCompleted. It becomes each time harder to really complete a task after it passes through ProtocolHandle InvFunction.

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: > I think that we need to re-run the tests after the last fix, @yongjiema, because the FifoSet had some problems in the ExceptWith command.
> 
> But I agree with the last comment I saw from you guys, @KickSeason, about the TaskCompleted. It becomes each time harder to really complete a task after it passes through ProtocolHandle InvFunction.

The test did in my local already included FIFOSet fix before preparing this PR.

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: The fix was wrong with a "minor" problem..,heuahahsu

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: May I know what's the "minor" problem?

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: As I said below, the HashSet that coordinates the `KnowHashes` use function `ExceptWith` for filtering and this function was not working probably on the new `FifoSet`. The last commit probably solved that, we also created some UT for being sure about that.

This surely could cause bad behavior.

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: Oh, I see, I have already noticed the problem, below is some part of my local FIFOSet during the testing before this PR:

```cs
// FIFOSet class

public IEnumerator<T> GetEnumerator()
{
    return data.Keys.OfType<T>().GetEnumerator();
}

IEnumerator IEnumerable.GetEnumerator()
{
    return data.Keys.GetEnumerator();
}
```

**Comment by vncoelho** [comment]
@shargon, if you want to apply and test the `AsParallel` search it also looks good. But I believe that this queue is not much much big, is it?

**Comment by shargon** [comment]
Without parallel is good for me

**Comment by vncoelho** [comment]
@erikzhang, fell free to merge or wait for the results on Testnet/Mainet of NEO 2x.

**Comment by yongjiema** [comment]
Sync the change (https://github.com/neo-project/neo/pull/900/commits/eb5ec679cccbe66a795a3ac02438b9d42dd8f3a7) from master-2.x

File: neo/Network/P2P/TaskManager.cs [hunk 3]
```diff
@@ -224,8 +224,8 @@ private void RequestTasks(TaskSession session)
             }
             if ((!HasHeaderTask || globalTasks[HeaderTaskHash] < MaxConncurrentTasks)
                 && (Blockchain.Singleton.HeaderHeight < session.StartHeight
-                    || (Blockchain.Singleton.HeaderHeight == session.StartHeight
-                        && Blockchain.Singleton.HeaderHeight == sessions.Select(x => x.Value.StartHeight).Max()
+                    || (Blockchain.Singleton.Height == Blockchain.Singleton.HeaderHeight
+                        && Blockchain.Singleton.HeaderHeight >= sessions.Select(x => x.Value.StartHeight).Max()
```
Comment (vncoelho) [inline neo/Network/P2P/TaskManager.cs]: @yongjiema, in my opinion it could even be the oposite:

`Blockchain.Singleton.HeaderHeight < sessions.Select(x => x.Value.StartHeight).Max()`

Request when we known that some session has a `StartHeight` higher than we are.

Anyway...let's keep it like this...aehuaheua

File: neo/Network/P2P/TaskManager.cs [hunk 4]
```diff
@@ -224,8 +224,8 @@ private void RequestTasks(TaskSession session)
...
                         && TimeProvider.Current.UtcNow.ToTimestamp() - 60 >= Blockchain.Singleton.GetBlock(Blockchain.Singleton.CurrentHeaderHash)?.Timestamp)))
```
Comment (vncoelho) [inline neo/Network/P2P/TaskManager.cs]: it should probably be `TimeProvider.Current.UtcNow.ToTimestamp() - 60000` here for master3.x, because we changed to `ms`. Could you double check @yongjiema?

In addition, please set this wait time in a variable before using, it will become more clear.

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: @vncoelho Seems like it's the same. https://github.com/neo-project/neo/blob/master/neo/Helper.cs#L170

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: Hey @yongjiema, this function is the same, correct, but the general use of timestamp changed. 
I will add a PR with these comments.

Could you please change to `ToTimestampMS`. Otherwise it will not be consistent with `Blockchain.Singleton.GetBlock(Blockchain.Singleton.CurrentHeaderHash)?.Timestamp`.

In addition, fell free to further investigate. We may have missed something during this timestamp changes.

Comment (erikzhang) [reply neo/Network/P2P/TaskManager.cs]: Maybe we should rename `Block.Timestamp` to `TimestampMS`.

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: I think that this was resolved, right? It was just a discussion, correct?

File: neo/Network/P2P/TaskManager.cs (hunk 4 above)
Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: I agree, @erikzhang, can we proceed with that refactoring in another PR?

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (erikzhang) [inline neo/Network/P2P/TaskManager.cs]: I think we should think more about this line.

Node A sends an `inv` for a block, and node B sends the same. In this case, the second message will be dropped. But if node A doesn't send `block`, we will stop sync.

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: O.o, makes sense, @erikzhang. ahuehauhea We are destroying master2x...
Just kidding, I think it will be ok there for now! ahueahuea

Can we personalize this `IEnumerable queue` a little bit more? If we set timestamps for the `objects`. Maybe also some improvements could come on the management of `ProtocolHandler`

Comment (shargon) [reply neo/Network/P2P/TaskManager.cs]: Then maybe we need the duplicates, i think that with the FIFO's patch and the own messages patch, will be enought, it was tested with this both patches and without this one?

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: I am testing a change for known hashes behaviour in ProtocolHandler related it, will share the code after the testing is done.

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: Please check the PR #1024 which is for 2x.

File: neo/Network/P2P/TaskManager.cs (hunk 1 above)
Comment (lock9) [inline neo/Network/P2P/TaskManager.cs]: Please, put this information in variables. This is unreadable :(

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (lock9) [inline neo/Network/P2P/TaskManager.cs]: Can you break this line or make this more readable in some other form? Thanks

Comment (yongjiema) [reply neo/Network/P2P/TaskManager.cs]: The change is outdated, please check PR #1024 for 2x.

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: I will also check there @yongjiema, sorry for the delay for looking into this.

Lets make it live again.

**Comment by vncoelho** [comment]
@yongjiema, now we gonna fly!! :D
aehuahuea

I just initialized a 100ms privatenet and our RPC nodes got stuck, lagging behind:
```cs
[Warning][22:03:25.762] chain sync: expected=2988 current=37 nodes=4
[Warning][22:03:25.771] chain sync: expected=2988 current=37 nodes=4
[Warning][22:03:25.786] chain sync: expected=2977 current=37 nodes=4
```

:dagger: Now we can test this PR in great style...aehuaheuaea
Nodes should not lag behind, in particular, in a controlled environment.

**Comment by yongjiema** [comment]
@vncoelho The change is outdated, please check PR #1024 for 2x.

**Comment by vncoelho** [comment]
@yongjiema, could please update these here?

Since now we have better tools on NEO3, such as `ms` blocks, it might be more worth our time to direct test these improvements on NEO3.

About NEO2, I see this in the limit of a bug and an improvement. In this sense, might we can really test this here first, focusing on NEO3 P2P performance.

@yongjiema, if you want I can guide you the steps for creating a privatenet for NEO3 using NeoCompiler-Eco. Anyway, as soon as you update this PR I will come back to this this as soon as possible for us to move in this important direction.

**Comment by yongjiema** [comment]
@vncoelho Please check the latest version.

**Comment by vncoelho** [comment]
@yongjiema, I tested here, it works but still with nodes lagging behind here.
We need to improve this. I will check the code again.

I think that one thing we should do asap is to comment the code.

For example, in another thread I saw that discussion about `VersionPayload`.

`Ack` is set to false all the time.

https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/Network/P2P/RemoteNode.cs#L55

https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/Network/P2P/RemoteNode.cs#L230

And then, we need another `OnAck` event: 

https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/Network/P2P/RemoteNode.cs#L106

Did you see this, @Tommo-L?

**Comment by yongjiema** [comment]
@vncoelho Any network changes are not included in 2.x? I did a full testing base on 2.x changes, it's working fine for a long time. BTW, can show some info for the nodes lagging behind?

**Comment by vncoelho** [comment]
It is an exaustive testing, @yongjiema, with 100ms privatenet network.

In our vision, the actors system, and our code improvements, should evolve to work perfect locally. Do you agree?
When we reach such instability locally we are going to be a big step ahead.

**Comment by Tommo-L** [comment]
> @yongjiema, I tested here, it works but still with nodes lagging behind here.
> We need to improve this. I will check the code again.
> 
> I think that one thing we should do asap is to comment the code.
> 
> For example, in another thread I saw that discussion about `VersionPayload`.
> 
> `Ack` is set to false all the time.
> 
> https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/Network/P2P/RemoteNode.cs#L55
> 
> https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/Network/P2P/RemoteNode.cs#L230
> 
> And then, we need another `OnAck` event:
> 
> https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/Network/P2P/RemoteNode.cs#L106
> 
> Did you see this, @Tommo-L?

We haven't meet this case. Could you describe your situation?

**Comment by Tommo-L** [comment]
@vncoelho A little strange, we meet this problem: the verack is always false.
image

**Comment by vncoelho** [comment]
@cloud8little, @Tommo-L, @ixje, could you also take a look at this PR?
I believe it has slightly good minor changes that can benefit our P2P.

**Comment by vncoelho** [comment]
@Tommo-L, that case I mentioned was more a code analyses about the use of `OnAck` event. I still did not understand it completely, why it is moved to `false` all the time.

**Comment by Tommo-L** [comment]
Mybe it's the duplicate connection problem? I will test in my local private net.

**Comment by Tommo-L** [comment]
> @Tommo-L, that case I mentioned was more a code analyses about the use of `OnAck` event. I still did not understand it completely, why it is moved to `false` all the time.

It works fine in my privatenet
image

Sometime it will be false, as the `Ack` message has not been received.  Would you describe the way you test.

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: @yongjiema, let's just keep the ping with `LastBlockHeight` and try merge this PR asap.
The `PendingHashes` could be moved to a new PR and, then, we discuss it a little further.

File: neo/Network/P2P/TaskManager.cs (hunk 1 above)
Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: Outdated. Fixed.

**Comment by yongjiema** [comment]
> @yongjiema, the PR is updated with master2x PR,right?
> 
> The `ShallDrop` was already merged there. Thus, in fact, it will make master3x like master2x.

You're correct.

**Comment by vncoelho** [comment]
Not possible right now, @shargon.

All the classes have no base UT. Someone need to create it first.

**Comment by shargon** [comment]
But it's hard to test it without tests

**Comment by vncoelho** [comment]
@shargon, that is why I took 5months+ to understand and test.

UT should never block a PR. I have bad experience with this, @igormcoelho as well.

You also worked in this kind of projects, @shargon. We surely do not want to make NEO like this.
UTs need to come with time and well designed.

**Comment by vncoelho** [comment]
@shargon, you and @belane also have that good tools for measuring client and consensus performance. Perhaps you can also try to see on that.

We are basically using NeocompilerEco enviroment and some automatic scripts for that.

But we believe that in the future good actors UT will also cover this part of the project.

**Comment by shargon** [comment]
@vncoelho We need time to test it if there are no UT, give me at least two days.

**Comment by shargon** [comment]
> Another reason is the current node's header reaches the highest one from the connection sessions, but it might not be updated for a long time, the fix is try to get the new headers if the current header equals the highest one and is not updated for a while.

@yongjiema how are you testing this scenario?

**Comment by shargon** [comment]
The issue 1 is already solved and now is only for the issue 2?

File: neo/Network/P2P/ProtocolHandler.cs [hunk 5]
```diff
@@ -314,6 +347,28 @@ private void OnVersionMessageReceived(VersionPayload payload)
...
+            timer.CancelIfNotNull();
+            base.PostStop();
+        }
+
+        private void RefreshPendingKnownHashes()
+        {
+            while (pendingKnownHashes.Count > 0)
+            {
+                KeyValuePair<UInt256, DateTime> item = pendingKnownHashes.First();
+                if (DateTime.UtcNow - item.Value <= PendingTimeout)
```
Comment (shargon) [inline neo/Network/P2P/ProtocolHandler.cs]: Use `TimeProvider`

File: neo/Network/P2P/TaskSession.cs [hunk 6]
```diff
@@ -16,6 +16,7 @@ internal class TaskSession
 
         public bool HasTask => Tasks.Count > 0;
         public uint StartHeight { get; }
+        public uint LastBlockIndex { get; set; }
```
Comment (shargon) [inline neo/Network/P2P/TaskSession.cs]: Could you add a `summary` for these properties?

**Comment by yongjiema** [comment]
> > Another reason is the current node's header reaches the highest one from the connection sessions, but it might not be updated for a long time, the fix is try to get the new headers if the current header equals the highest one and is not updated for a while.
> 
> @yongjiema how are you testing this scenario?

I tested on my local private chain.

File: neo/Network/P2P/ProtocolHandler.cs (hunk 5 above)
Comment (yongjiema) [reply neo/Network/P2P/ProtocolHandler.cs]: Think the code is from the existing project, I did want to change it, but I found many places are using `DateTime.UtcNow`, so I keep it as the original version.

**Comment by shargon** [comment]
But how can I force this scenario?

File: neo/Network/P2P/TaskManager.cs (hunk 2 above)
Comment (erikzhang) [reply neo/Network/P2P/TaskManager.cs]: I still think we should remove this.

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: So, let's remove this and open it in another PR.

I think that we added it before on master2.x. But we can separate it here and analyse in another moment.

Comment (vncoelho) [reply neo/Network/P2P/TaskManager.cs]: > I think we should think more about this line.
> 
> Node A sends an `inv` for a block, and node B sends the same. In this case, the second message will be dropped. But if node A doesn't send `block`, we will stop sync.

With `PendingHashes` it will not happen in a loop, since the hash will expire.

File: neo/Network/P2P/ProtocolHandler.cs [hunk 7]
```diff
@@ -22,11 +22,11 @@ internal class ProtocolHandler : UntypedActor
         public class SetFilter { public BloomFilter Filter; }
         internal class Timer { }
 
-        private class PendingKnownHashesCollection : KeyedCollection<UInt256, KeyValuePair<UInt256, DateTime>>
+        private class PendingKnownHashesCollection : KeyedCollection<UInt256, (UInt256, DateTime)>
         {
-            protected override UInt256 GetKeyForItem(KeyValuePair<UInt256, DateTime> item)
+            protected override UInt256 GetKeyForItem((UInt256, DateTime) item)
```
Comment (vncoelho) [inline neo/Network/P2P/ProtocolHandler.cs]: I prefer these tuples than keyvaluepair. Nice job, @erikzhang.

**Comment by vncoelho** [comment]
@yongjiema, can you merge the PR locally with the current Master?

In addition, @erikzhang is still concerned about `shallDrop`. However, I believe the `shalldrop` is really a problem without the `pendinghashes`. 
On the other hand, with the `pendinghashes` the problem Erik's mentioned may had been solved, right? Could you take a look on that?

**Comment by erikzhang** [comment]
The commits with the changes to workflow files can not be merged to your repository.

File: src/neo/Network/P2P/TaskManager.cs [hunk 8]
```diff
@@ -266,5 +285,13 @@ internal protected override bool IsHighPriority(object message)
                     return false;
             }
         }
+
+        internal protected override bool ShallDrop(object message, IEnumerable queue)
+        {
+            if (!(message is TaskManager.NewTasks tasks)) return false;
+            // Remove duplicate tasks
+            if (queue.OfType<TaskManager.NewTasks>().Any(x => x.Payload.Type == tasks.Payload.Type && x.Payload.Hashes.SequenceEqual(tasks.Payload.Hashes))) return true;
```
Comment (erikzhang) [inline src/neo/Network/P2P/TaskManager.cs]: This is the last question. I still believe we should remove this.
https://github.com/neo-project/neo/pull/899#discussion_r315172978

Comment (yongjiema) [reply src/neo/Network/P2P/TaskManager.cs]: This version can proceed the same `inv` after 1 min.

https://github.com/neo-project/neo/blob/75f4470356aa3ef97d5752932dd0214a80ad4953/src/neo/Network/P2P/ProtocolHandler.cs#L42

**Comment by vncoelho** [comment]
@shargon and @lock9, these changes were already merged on Master2x.
Thus, I think we should merge this here as soon as possible for: 1) testing it daily with other features; 2) moving forward to the next stages.

UTs can come at any time for these classes, it is a need that any one fulfilled yet.

File: src/neo/Network/P2P/TaskManager.cs (hunk 8 above)
Comment (vncoelho) [reply src/neo/Network/P2P/TaskManager.cs]: Still there could be some attack from the node, which also tracks this `1min` interval and makes that for locking a node...aheuahuea
However, I think it is not worth considering this right now.

Comment (vncoelho) [reply src/neo/Network/P2P/TaskManager.cs]: @erikzhang @yongjiema

**Comment by vncoelho** [comment]
I agree with the order, @shargon, better to try the feature on NEO3 first.
I think this was a special case in which we were really trying to improve NEO2. There it had happened in two different occasions. This PR was split there.
