### PR TITLE
Fix 1244 Mempool.ReverifyTransactions

### LINKED ISSUE #1244: Transactions with insufficient funds can be on-chain and lead to consensus service stuck
**Describe the bug**
Transactions with insufficient funds can be on-chain and lead to consensus service stuck.

**To Reproduce**
1. Run one seed node.
2. Run a single consensus node, connect to the seed node
3. Run an external node.
4. Withdraw the initial NEO/GAS and send 100k GAS to a sender wallet.
5. Open the sender wallet, use (sendfrom)rpc request to send about 800k requests, 0.00000001 GAS/request to another account.
6. Around 1hour later, consensus service stuck, not generating blocks anymore.

when the consensus service stuck, there is only 459+GAS with the account.

**Expected behavior**
Those transactions with not enough gas check should be discarded.
Consensus service should not stuck.

**Screenshots**
3171573801636_ pic_hd
4281573804642_ pic_hd
4291573804681_ pic

**Platform:**
 - OS: Ubuntu18.04
 - Version
neo-cli: master #470 
neo: master #1150 + pr1220

### PR DESCRIPTION
**Pull request by Tommo-L**
close #1244
relate to #1183

### CODE REVIEW

File: neo/SmartContract/Native/Tokens/Nep5Token.cs [hunk 1]
```diff
@@ -87,15 +87,25 @@ internal protected virtual void Mint(ApplicationEngine engine, UInt160 account,
...
-            if (amount.IsZero) return;
+            if (amount.IsZero) return amount;
             StorageKey key = CreateAccountKey(account);
             StorageItem storage = engine.Snapshot.Storages.GetAndChange(key);
             TState state = new TState();
             state.FromByteArray(storage.Value);
-            if (state.Balance < amount) throw new InvalidOperationException();
+            if (state.Balance < amount)
+            {
+                amount = state.Balance;
```
Comment (shargon) [inline neo/SmartContract/Native/Tokens/Nep5Token.cs]: We are sure that in this case, the execution was `FAULT`?

File: neo/SmartContract/Native/Tokens/Nep5Token.cs [hunk 2]
```diff
@@ -87,15 +87,25 @@ internal protected virtual void Mint(ApplicationEngine engine, UInt160 account,
...
+            }
```
Comment (erikzhang) [inline neo/SmartContract/Native/Tokens/Nep5Token.cs]: I think `state.Balance < amount` is impossible.

File: neo/SmartContract/Native/Tokens/Nep5Token.cs (hunk 1 above)
Comment (Tommo-L) [reply neo/SmartContract/Native/Tokens/Nep5Token.cs]: If in a normal contract, it's `FAULT`, but this case happens in `GasToken.OnPersist`. We need to discuss whether it is allowed to accept failed transactions.

File: neo/SmartContract/Native/Tokens/Nep5Token.cs (hunk 2 above)
Comment (Tommo-L) [reply neo/SmartContract/Native/Tokens/Nep5Token.cs]: Agree, it should not happen, I will change this PR.

Comment (Tommo-L) [reply neo/SmartContract/Native/Tokens/Nep5Token.cs]: fixed

**Comment by cloud8little** [comment]
consensus service will continue generating block after the fix, the old one is supposed to stuck on height 32.  As below: 
4341574129235_ pic_hd

While still need to check whether the balance of the account is correct at last.

**Comment by cloud8little** [comment]
Checked the balance is correct. initial balance 10K, After send 10-8 gas/request, total sys fee: 9875.00000000 total net fee: 124.25416250 balance should be: 0.7458375, result is also 0.7458375.
4351574132584_ pic

**Comment by Tommo-L** [comment]
> Any UT for testing this specific case?

waiting for me, I'm adding the UT

File: neo.UnitTests/Ledger/UT_MemoryPool.cs [hunk 3]
```diff
@@ -171,6 +208,36 @@ public void BlockPersistMovesTxToUnverifiedAndReverification()
...
+            snapshot.Commit();
+
+            // Persist block and reverify all the txs in mempool, but all the txs will be discarded
+            _unit.UpdatePoolForBlockPersisted(block, snapshot);
+            _unit.SortedTxCount.Should().Be(0);
+            _unit.UnverifiedSortedTxCount.Should().Be(0);
+
+            // Withdraw the GAS by minting gas to the sender
+            NativeContract.GAS.Mint(applicationEngine, sender, balance);
+            snapshot.Commit();
```
Comment (shargon) [inline neo.UnitTests/Ledger/UT_MemoryPool.cs]: Can be avoided this commit?

File: neo.UnitTests/Ledger/UT_MemoryPool.cs [hunk 4]
```diff
@@ -171,6 +208,36 @@ public void BlockPersistMovesTxToUnverifiedAndReverification()
             _unit.UnverifiedSortedTxCount.Should().Be(0);
         }
 
+        [TestMethod]
+        public void BlockPersistAndReverificationWillAbandonTxAsBalanceTransfered()
```
Comment (shargon) [inline neo.UnitTests/Ledger/UT_MemoryPool.cs]: I reverted the `Memory Pool` changes and this UT pass, so it not prove the specific case.

Comment (Tommo-L) [reply neo.UnitTests/Ledger/UT_MemoryPool.cs]: I got, I should fix the balance, update later

Comment (Tommo-L) [reply neo.UnitTests/Ledger/UT_MemoryPool.cs]: done

**Comment by shargon** [comment]
Wait for @Tommo-L because maybe adding something we can fix https://github.com/neo-project/neo/pull/1248 too

**Comment by vncoelho** [comment]
There was a TODO on a draft I left locally here last week. I think this PR covers that. Nice job.

**Comment by Tommo-L** [comment]
Thanks @vncoelho it already contains the lock in `SendersFeeMonitor.AddSenderFee/RemoveSenderFee` methods.

**Comment by vncoelho** [comment]
I see, @Tommo-L, it should be fine. However, maybe there is still something bad.
Because we are considering that the `verifiedSorted` already contain that tx, but it does not.

While you add to `SendersFeeMonitor` you could block another `tx` to enter, and, then, later you remove that `tx` below, something like that. I am not sure...aheuahuea

**Comment by Tommo-L** [comment]
@vncoelho I got your point, but `ReverifyTransactions` only invoked by `MemoryPool.UpdatePoolForBlockPersisted` and `MemoryPool.ReVerifyTopUnverifiedTransactionsIfNeeded`, which both called from a single thread (the Blockchain actor), I think those case will not happen.

**Comment by vncoelho** [comment]
Perfect, @Tommo-L, let's keep this is mind in case we see anything in this direction.
It is always good to wonder.

Lets move forward because the fix is surely needed asap.
