### PR TITLE
apply strict enum checking

### LINKED ISSUE #1231: Strict enum value checking
**Summary**
Enum's in C# are not strict when it comes to casting. e.g. 

```C#
public enum VMState : byte
    {
        NONE = 0,

        HALT = 1 << 0,
        FAULT = 1 << 1,
        BREAK = 1 << 2,
    }

VMState state = (VMState) 8; <- works fine
```

This can lead to various issues or performance degradation; 
* In NEO2 a contract was successfully deployed with an invalid `ContractParameterType` (#228). The impact for this specific case was low but could be worse.  
* Objects can pass deserialization with invalid data ([example](https://github.com/neo-project/neo/blob/f1d643430966b9cc13f66ecb4ef2cfb462ccee85/neo/Ledger/TransactionState.cs#L32)) leading to unnecessary resource consumption, where we could have thrown an exception, aborted early and save resources.
* The VM can run longer than necessary with invalid data ([interop layer example that could abort early](https://github.com/neo-project/neo/blob/f1d643430966b9cc13f66ecb4ef2cfb462ccee85/neo/SmartContract/InteropService.cs#L576))

**Do you have any solution you want to propose?**
I'd like to suggest we create some helper method that does strict Enum value checking and throws an exception if it is out of bounds.

So the above could look something like
```C#
VMState state = Helper.StrictEnumFrom<VMState>(8); <- raises FormatException
```

**Where in the software does this update applies to?**
Everywhere

I'm interested to hear thoughts on the idea

### PR DESCRIPTION
**Pull request by ixje**
Close #1231 

~@shargon the only way it would build was by changing the `LangVersion` to 7.3, so I'm PR'ing with that to begin with.~

### CODE REVIEW

**Comment by shargon** [comment]
I haven't got any error with `preview` in my local. I will check with travis.

**Comment by ixje** [comment]
what visual studio version do you run? I have `Community 2017`

**Comment by shargon** [comment]
> what visual studio version do you run? I have Community 2017

Community 2019

File: neo/Helper.cs [hunk 1]
```diff
@@ -320,5 +320,34 @@ public static IConfigurationRoot LoadConfig(string config)
...
+        {
+            T state = (T)Enum.ToObject(typeof(T), value);
+            if (!EnumValueCache<T>.definedValues.Contains(state))
+                throw new FormatException();
+            return state;
+        }
+
+        public static T StrictEnumParse<T>(string value) where T : Enum
+        {
+            T state = (T)Enum.Parse(typeof(T), value);
```
Comment (shargon) [inline neo/Helper.cs]: We should define if we allow or not `ignoreCases` 
My vote: yes

File: neo/Helper.cs [hunk 2]
```diff
@@ -320,5 +320,34 @@ public static IConfigurationRoot LoadConfig(string config)
                 .AddJsonFile(configFile, true)
                 .Build();
         }
+
+        public static T StrictEnum<T>(int value) where T : Enum
+        {
```
Comment (shargon) [inline neo/Helper.cs]: If is not used, we should remove this method

Comment (ixje) [reply neo/Helper.cs]: I thought it would be good to have it already there for the moment somebody needs it.

Comment (shargon) [reply neo/Helper.cs]: I think that all of our enums will be `byte`

File: neo/Helper.cs (hunk 1 above)
Comment (ixje) [reply neo/Helper.cs]: I removed `StrictEnumParse` completely.  It was replacing `Enum.Parse`, but that already fails if the entry doesn't exist in the Enum.

File: neo/Helper.cs [hunk 3]
```diff
@@ -320,5 +320,18 @@ public static IConfigurationRoot LoadConfig(string config)
...
+            T state = (T)Enum.ToObject(typeof(T), value);
+            if (!EnumValueCache<T>.definedValues.Contains(state))
+                throw new FormatException();
+            return state;
+        }
+
+        private static class EnumValueCache<T> where T : Enum
+        {
+            public static readonly HashSet<T> definedValues = new HashSet<T>((T[])Enum.GetValues(typeof(T)));
+        }
```
Comment (erikzhang) [inline neo/Helper.cs]: I prefer to use `Enum.IsDefined()`.

File: neo/Helper.cs [hunk 4]
```diff
@@ -320,5 +320,18 @@ public static IConfigurationRoot LoadConfig(string config)
                 .AddJsonFile(configFile, true)
                 .Build();
         }
+
+        public static T StrictEnum<T>(byte value) where T : Enum
+        {
+            T state = (T)Enum.ToObject(typeof(T), value);
+            if (!EnumValueCache<T>.definedValues.Contains(state))
+                throw new FormatException();
```
Comment (erikzhang) [inline neo/Helper.cs]: I think we should throw `ArgumentOutOfRangeException` here. But the caller may want to throw `FormatException`. So the best idea is to throw exception in the caller.

File: neo/Helper.cs (hunk 3 above)
Comment (ixje) [reply neo/Helper.cs]: Can you explain why? It is 2x slower than with this hashset. See https://github.com/neo-project/neo/issues/1231#issuecomment-552860288

Comment (erikzhang) [reply neo/Helper.cs]: My test:

```c#
enum TestEnum : byte
{
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
}

static class EnumValueCache<T> where T : Enum
{
    public static readonly HashSet<T> DefinedValues = new HashSet<T>((T[])Enum.GetValues(typeof(T)));
}

static T StrictEnum<T>(byte value) where T : Enum
{
    T state = (T)Enum.ToObject(typeof(T), value);
    if (!EnumValueCache<T>.DefinedValues.Contains(state))
        throw new FormatException();
    return state;
}

static void Main()
{
    Stopwatch stopwatch = new Stopwatch();
    TestEnum five = TestEnum.Five;
    byte fiveValue = (byte)TestEnum.Five;

    stopwatch.Start();
    for (int i = 0; i < 100000; i++)
    {
        Enum.IsDefined(typeof(TestEnum), five);
    }
    stopwatch.Stop();
    Console.WriteLine($"IsDefined: {stopwatch.Elapsed.TotalMilliseconds} ms");

    stopwatch.Restart();
    for (int i = 0; i < 100000; i++)
    {
        Enum.IsDefined(typeof(TestEnum), TestEnum.Five);
        StrictEnum<TestEnum>(fiveValue);
    }
    stopwatch.Stop();
    Console.WriteLine($"StrictEnum: {stopwatch.Elapsed.TotalMilliseconds} ms");
}
```

IsDefined: 41.8113 ms
StrictEnum: 121.79360000000001 ms

File: neo/Helper.cs [hunk 5]
```diff
@@ -320,5 +320,18 @@ public static IConfigurationRoot LoadConfig(string config)
                 .AddJsonFile(configFile, true)
                 .Build();
         }
+
+        public static T StrictEnum<T>(byte value) where T : Enum
+        {
+            T state = (T)Enum.ToObject(typeof(T), value);
+            if (!EnumValueCache<T>.definedValues.Contains(state))
+                throw new ArgumentOutOfRangeException();
```
Comment (erikzhang) [inline neo/Helper.cs]: I think the exception should be thrown by the caller. Because we don't know what exception should be thrown. Otherwise, the caller should catch the exception the re-throw the correct one.

File: neo/Helper.cs (hunk 3 above)
Comment (ixje) [reply neo/Helper.cs]: I don't think this is a completely fair comparison. We're comparing a generic function against an inlined implementation that does not have the function call overhead,  that only deals with 1 enum type and doesn't check if it needs to raise any exceptions (and maybe even benefits from internal optimizations because it's all in one loop).

Here are my results when I make the code around `Enum.IsDefined` generic and put it into its own helper function. Reducing boilerplate code was part of the idea of the PR.

**with fixed value**
`Enum.IsDefined` best case - 26.602ms (while actually averaging around 28.xx)
`StrictEnum` worst case - 23.6009ms


**with changing value**
`Enum.IsDefined` best case - 32.0974ms (while actually averaging around 33.xx)
`StrictEnum` worst case - 23.966ms


It is not the 2x difference that my previous test showed, but it is still faster. The difference in the old results might be caused by the machine used (old laptop then vs desktop now).

If we still prefer `Enum.IsDefined` then no problem but to me it seems like the hashset solution is the faster and better option because neo is a long running program with varying inputs to be casted.

File: neo/Helper.cs (hunk 5 above)
Comment (ixje) [reply neo/Helper.cs]: uhh, so the feedback is
- drop this helper function
- type boiler plate `if (!Enum.IsDefined(typeof(something), enum_variable) raise component_specific_exception` in all places that the project did not do enum validation

correct?

Comment (erikzhang) [reply neo/Helper.cs]: Yes.

File: neo/Consensus/ConsensusMessage.cs [hunk 6]
```diff
@@ -24,7 +24,11 @@ protected ConsensusMessage(ConsensusMessageType type)
 
         public virtual void Deserialize(BinaryReader reader)
         {
-            if (Type != (ConsensusMessageType)reader.ReadByte())
+            ConsensusMessageType cmt = (ConsensusMessageType)reader.ReadByte();
+            if (!Enum.IsDefined(typeof(ConsensusMessageType), cmt))
```
Comment (shargon) [inline neo/Consensus/ConsensusMessage.cs]: Move this lines to the constructor

File: neo/Wallets/SQLite/VerificationContract.cs [hunk 7]
```diff
@@ -15,6 +15,11 @@ public void Deserialize(BinaryReader reader)
         {
             reader.ReadSerializable<UInt160>();
             ParameterList = reader.ReadVarBytes().Select(p => (ContractParameterType)p).ToArray();
+            foreach (var parameter in ParameterList)
```
Comment (shargon) [inline neo/Wallets/SQLite/VerificationContract.cs]: This could be done in the `Linq` query, and save one `foreach`

Comment (ixje) [reply neo/Wallets/SQLite/VerificationContract.cs]: @shargon how would I do that? I tried something like this
```C#
ParameterList.Select(p => Enum.IsDefined(typeof(ContractParameterType),p) == false).Any(throw new FormatException()); 
```
but it does not allow me to throw an exception. `foreach` can't be that expensive since we break out of it on the first invalid enum, right?

File: neo/Consensus/ConsensusMessage.cs (hunk 6 above)
Comment (ixje) [reply neo/Consensus/ConsensusMessage.cs]: I don't understand the suggestion. The type needs to be read from the BinaryReader and the result (`cmt`) has 2 usages
1.  check for an invalid enum type
2. next check if it equals to whatever `Type` the message already had.

**Comment by ixje** [comment]
> Hello.
> This is just an extra layer of security, right? It is blocking values outside the enum range, is that it?

Yes, it fails early when values are outside the enum range. See the issue mentioned why this matters.
> Did you do this for "all enums" or just for specific cases?

 It is applied to all enums except `Flag` based enums (as per this comment https://github.com/neo-project/neo/issues/1231#issuecomment-552839091)

> How to test this? Is there any way to check what has changed?
> 
> Request for changes reason: no UT, sorry 😅

I'm not adding unit tests until there is an agreement on the current implementation. I wrote unit tests for the first iteration and then had to drop it again, so I want to save my time and sanity here.

**Comment by lock9** [comment]
@ixje  I like your changes. You have my approval, if you add UT, but yes, wait for more people before 'wasting'  your time 😅

File: neo/Consensus/ConsensusMessage.cs (hunk 6 above)
Comment (shargon) [reply neo/Consensus/ConsensusMessage.cs]: If you check that the Type is a valid one in the constructor, you don't need to change this code.

File: neo/Wallets/SQLite/VerificationContract.cs (hunk 7 above)
Comment (shargon) [reply neo/Wallets/SQLite/VerificationContract.cs]: Check my changes, you can `throw` inside the linq query

File: neo/Consensus/ConsensusMessage.cs (hunk 6 above)
Comment (shargon) [reply neo/Consensus/ConsensusMessage.cs]: @ixje In this particular case it will check that the value is exactly the same as the constructor. So i think that is not needed.

File: neo/Consensus/ChangeView.cs [hunk 8]
```diff
@@ -32,6 +33,8 @@ public override void Deserialize(BinaryReader reader)
             base.Deserialize(reader);
             Timestamp = reader.ReadUInt64();
             Reason = (ChangeViewReason)reader.ReadByte();
+            if (!Enum.IsDefined(typeof(ChangeViewReason), Reason))
```
Comment (erikzhang) [inline neo/Consensus/ChangeView.cs]: We don't need to check it here. If we add new reason in the future, it can be compatible with the current version.

File: neo/Network/P2P/Message.cs [hunk 9]
```diff
@@ -102,6 +102,8 @@ void ISerializable.Deserialize(BinaryReader reader)
         {
             Flags = (MessageFlags)reader.ReadByte();
             Command = (MessageCommand)reader.ReadByte();
+            if (!Enum.IsDefined(typeof(MessageCommand), Command))
```
Comment (erikzhang) [inline neo/Network/P2P/Message.cs]: We don't need to check it here. If we add new command in the future, it can be compatible with the current version.

File: neo/Network/P2P/Message.cs [hunk 10]
```diff
@@ -152,6 +154,8 @@ internal static int TryDeserialize(ByteString data, out Message msg)
                 Command = (MessageCommand)header[1],
                 _payload_compressed = length <= 0 ? new byte[0] : data.Slice(payloadIndex, (int)length).ToArray()
             };
+            if (!Enum.IsDefined(typeof(MessageCommand), msg.Command))
```
Comment (erikzhang) [inline neo/Network/P2P/Message.cs]: We don't need to check it here. If we add new command in the future, it can be compatible with the current version.

File: neo/Network/P2P/Payloads/Cosigner.cs [hunk 11]
```diff
@@ -32,6 +32,8 @@ void ISerializable.Deserialize(BinaryReader reader)
         {
             Account = reader.ReadSerializable<UInt160>();
             Scopes = (WitnessScope)reader.ReadByte();
+            if (!Enum.IsDefined(typeof(WitnessScope), Scopes))
```
Comment (erikzhang) [inline neo/Network/P2P/Payloads/Cosigner.cs]: `WitnessScope` has a `Flags` attribute, so it can't be check in this way.

File: neo/Network/P2P/Message.cs (hunk 9 above)
Comment (ixje) [reply neo/Network/P2P/Message.cs]: The idea of strict enum checking is to fail early. Without this check here I can create a message with a fake command that 
1. the system will first try to decompress
2. next all `IP2PPlugin`s will receive it 
3. and finally it will silently be ignored because there is no matching case in the protocolhandler. 

Instead with this check it will never waste any resources on decompressing and prevents it reaching `P2PPlugin`s. It will drop the remote node on the first invalid message format, which is the same behaviour we have when a payload inside the message is invalid.

File: neo/Network/P2P/Payloads/Cosigner.cs (hunk 11 above)
Comment (ixje) [reply neo/Network/P2P/Payloads/Cosigner.cs]: it was a suggestion by shargon, but i'll remove it again.

File: neo/Consensus/ChangeView.cs (hunk 8 above)
Comment (ixje) [reply neo/Consensus/ChangeView.cs]: it's been a very long time that i looked at the consensus code, but what prevents me from sending a `ConsensusPayload` with an invalid message that gets processed unnecessarily (see https://github.com/neo-project/neo/pull/1254#discussion_r349537663 what I mean with unnecessary processing)?

Comment (erikzhang) [reply neo/Consensus/ChangeView.cs]: The consensus message doesn't need to be dropped even if I don't know the changeview reason. So this check is unnecessary because we may add new reasons in the future.

File: neo/Network/P2P/Message.cs (hunk 9 above)
Comment (erikzhang) [reply neo/Network/P2P/Message.cs]: That is because we don't know the message format, but maybe the `IP2PPlugin` may know it. This could be a protocol extension plugin.

**Comment by erikzhang** [comment]
@ixje

**Comment by ixje** [comment]
Sorry for no reply, I ignored github for 2 days because I had to focus and push out a lot of code.
