### PR TITLE
Avoid call onPayment on specific cases

### LINKED ISSUE #2093: Oracle contract doesn't implement NEP-17 onPayment method
**Describe the bug**
Oracle contract mints some GAS in its `request` method which in turns invokes `onPayment` on Oracle contract which just doesn't exist at the moment, so the call fails.

**Expected behavior**
Oracle requests should work, thus `onPayment` needs to be implemented in Oracle contract. I think we need to check for token type inside and only accept GAS (make transfers of any other tokens fail).

### PR DESCRIPTION
**Pull request by shargon**
Close #2093
Alternative to #2094

We should avoid this call not only for Oracle, also for the contract who receive GAS and only accept NEO, they should receive the GAS

### CODE REVIEW

**Comment by Tommo-L** [comment]
It's good for me.

**Review by Tommo-L — APPROVED** [review]

**Review by vncoelho — APPROVED** [review]

File: src/neo/SmartContract/Native/Tokens/Nep17Token.cs [hunk 1]
```diff
@@ -67,10 +67,10 @@ internal protected virtual void Mint(ApplicationEngine engine, UInt160 account,
             state.Balance += amount;
             storage = engine.Snapshot.Storages.GetAndChange(CreateStorageKey(Prefix_TotalSupply), () => new StorageItem(BigInteger.Zero));
             storage.Add(amount);
-            PostTransfer(engine, null, account, amount);
+            PostTransfer(engine, null, account, amount, callOnPayment);
         }
 
-        internal protected virtual void Burn(ApplicationEngine engine, UInt160 account, BigInteger amount)
+        internal protected virtual void Burn(ApplicationEngine engine, UInt160 account, BigInteger amount, bool callOnPayment)
```
Comment (erikzhang) [inline src/neo/SmartContract/Native/Tokens/Nep17Token.cs:73]: It is impossible to call `callOnPayment` in `Burn` because `to` is always `null`.

File: src/neo/SmartContract/Native/Tokens/NeoToken.cs [hunk 2]
```diff
@@ -64,7 +64,7 @@ private void DistributeGas(ApplicationEngine engine, UInt160 account, NeoAccount
 
             BigInteger gas = CalculateBonus(engine.Snapshot, state.VoteTo, state.Balance, state.BalanceHeight, engine.Snapshot.PersistingBlock.Index);
             state.BalanceHeight = engine.Snapshot.PersistingBlock.Index;
-            GAS.Mint(engine, account, gas);
+            GAS.Mint(engine, account, gas, false);
```
Comment (roman-khimov) [inline src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: This is the most interesting thing here and I'm really not sure about it. There might be scenarios when NEO-holding contract would like to do something with generated GAS and this makes it less convenient, furthermore this can effectively lock GAS generated into contract's address. Maybe we should have `true` here and leave this as contract's responsibility (if it accepts NEO, it must handle this minted GAS in some way also).

Comment (shargon) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: I think that GAS mint should be avoided of this logic

File: src/neo/SmartContract/Native/Tokens/Nep17Token.cs (hunk 1 above)
Comment (shargon) [reply src/neo/SmartContract/Native/Tokens/Nep17Token.cs]: Done

**Comment by Tommo-L** [comment]
Conflicts

File: src/neo/SmartContract/Native/Tokens/NeoToken.cs (hunk 2 above)
Comment (Tommo-L) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: > if it accepts NEO, it must handle this minted GAS in some way

I agree

Comment (erikzhang) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: Maybe this should be `true`.

Comment (shargon) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: What should you do if you want to receive NEO, and not GAS?

Comment (roman-khimov) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs]: Check `from`? If it's not minted (non-null), reject it, if it is --- deal with it.

Comment (shargon) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs]: But every neo transaction, mint gas

Comment (Tommo-L) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs]: In most cases, it's non-contract address.

**Review by erikzhang — APPROVED** [review]

File: src/neo/SmartContract/Native/Tokens/NeoToken.cs [hunk 3]
```diff
@@ -64,7 +64,7 @@ private void DistributeGas(ApplicationEngine engine, UInt160 account, NeoAccount
 
             BigInteger gas = CalculateBonus(engine.Snapshot, state.VoteTo, state.Balance, state.BalanceHeight, engine.Snapshot.PersistingBlock.Index);
             state.BalanceHeight = engine.Snapshot.PersistingBlock.Index;
-            GAS.Mint(engine, account, gas);
+            GAS.Mint(engine, account, gas, true);
```
Comment (Tommo-L) [inline src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: Maybe we should set it `false`.

Comment (erikzhang) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: Why?

Comment (Tommo-L) [reply src/neo/SmartContract/Native/Tokens/NeoToken.cs:67]: Because this part GAS is not from someone else, but from auto-claimed.
