### PR TITLE
[Core P2P] fix the bug

### LINKED ISSUE #3694: CLI can't get Peers
**Describe the bug**
Tried the latest master branch, build CLI on windows. It can't get peers!

**To Reproduce**
1. git clone `master`
2. build CLI
3. run CLI, `show state`

**Expected behavior**
It should get peers to sync.

**Screenshots**

Image

**Platform:**
All

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

There is a bug in the P2P as introduced in https://github.com/neo-project/neo/pull/3655, previously we can send the Version to remote node before having the remote Version, but in that pr, it enforced using Version while its still Null, causing Null Object exception. 

Close #3694

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/Neo/Network/P2P/RemoteNode.cs [hunk 1]
```diff
@@ -234,7 +234,11 @@ internal static Props Props(NeoSystem system, LocalNode localNode, object connec
         private void SendMessage(Message message)
         {
             ack = false;
-            SendData(ByteString.FromBytes(message.ToArray(Version.AllowCompression)));
+            // Here it is possible that we dont have the Version message yet,
+            // so we need to send the message uncompressed
+            SendData(message.Command == MessageCommand.Version
+                ? ByteString.FromBytes(message.ToArray())
+                : ByteString.FromBytes(message.ToArray(Version.AllowCompression)));
```
Comment (cschuchardt88) [inline src/Neo/Network/P2P/RemoteNode.cs:241]:
```suggestion
            // Here it is possible that we dont have the Version message yet,
            // so we need to send the message uncompressed
            SendData(ByteString.FromBytes(message.ToArray(Version?.AllowCompression ?? false)));
```
`ByteString.FromBytes(message.ToArray())` is telling the client that packet is compressed. Even though is not.

Removes compression flag for packet. So client doesn't try to decompress data that isn't compressed.
https://github.com/neo-project/neo/blob/befe7f64d2ef7fa8abfb02864f63bc0bcac07875/src/Neo/Network/P2P/Message.cs#L150-L152

**`ToArray()` calls `Serialize`**:
https://github.com/neo-project/neo/blob/befe7f64d2ef7fa8abfb02864f63bc0bcac07875/src/Neo/Extensions/IO/ISerializableExtensions.cs#L24-L31

Which in turn doesn't remove the compression `flag`.
https://github.com/neo-project/neo/blob/befe7f64d2ef7fa8abfb02864f63bc0bcac07875/src/Neo/Network/P2P/Message.cs#L130-L135

**Review by cschuchardt88 — CHANGES_REQUESTED** [review]

**Review by cschuchardt88 — APPROVED** [review]

**Review by superboyiii — APPROVED** [review]

**Review by nan01ab — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
Good catch!
