### PR TITLE
fix block_cache

### LINKED ISSUE #2088: [master-2.x] InvPayload contains null hash
image

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #2088 as this issue would also likely to occur in Neo3.

Logic similar to #2110

### CODE REVIEW

File: src/neo/Ledger/Blockchain.cs [hunk 1]
```diff
@@ -62,7 +63,7 @@ private class UnverifiedBlocksList { public LinkedList<Block> Blocks = new Linke
         private readonly IActorRef txrouter;
         private readonly List<UInt256> header_index = new List<UInt256>();
         private uint stored_header_count = 0;
-        private readonly Dictionary<UInt256, Block> block_cache = new Dictionary<UInt256, Block>();
+        private readonly ConcurrentDictionary<UInt256, Block> block_cache = new ConcurrentDictionary<UInt256, Block>();
         private readonly Dictionary<uint, UnverifiedBlocksList> block_cache_unverified = new Dictionary<uint, UnverifiedBlocksList>();
```
Comment (shargon) [inline src/neo/Ledger/Blockchain.cs:67]: why not with `block_cache_unverified`?

Comment (Qiao-Jin) [reply src/neo/Ledger/Blockchain.cs:67]: block_cache_unverified is not called by different threads

Comment (shargon) [reply src/neo/Ledger/Blockchain.cs:67]: It's the performance of `ConcurrentDictionary` to much worse? have you test it? Maybe we should use always a thread-safe version, otherwise it's a little dangerous.

Comment (Qiao-Jin) [reply src/neo/Ledger/Blockchain.cs:67]: I searched performance comparing between these 2 & it seems that their performance are much different:
https://github.com/dotnet/runtime/issues/667
https://cc.davelozinski.com/c-sharp/dictionary-vs-concurrentdictionary
But yes we can also change block_cache_unverified to ConcurrentDictionary as there are not so many block messages on network.

Comment (shargon) [reply src/neo/Ledger/Blockchain.cs]: What do you think @erikzhang ?

Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: How about use `IImmutableDictionary`?

**Comment by erikzhang** [comment]
How about use `IImmutableDictionary`?

File: src/neo/Ledger/Blockchain.cs (hunk 1 above)
Comment (erikzhang) [reply src/neo/Ledger/Blockchain.cs]: If it is not used in multiple threads, it should use `Dictionary`.

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
> How about use IImmutableDictionary?

Here said that it's less efficient. https://stackoverflow.com/a/48682387

**Review by erikzhang — APPROVED** [review]
