### PR TITLE
Fix isDefault

### LINKED ISSUE #2450: NEP-6 inconsistency
**Problem**

In the NEP-6 standard an `Account` object has a property `isDefault`, which seems to be an inconsistency in the Neo space, where most (if not any) JSON objects are consistently written in lowercase. See an open issue about this [here](https://github.com/neow3j/neow3j/issues/525).

Even here in the [NEP6Account.cs](https://github.com/neo-project/neo/blob/d1f015ccca6019fd9fdb7ff920673ef013a8499d/src/neo/Wallets/NEP6/NEP6Account.cs#L36) the NEP-6 is not strictly followed.

**Suggestion**

Even though the NEP-6 proposal is final, for consistency reasons the property `isDefault` should either be corrected to lowercase (`isdefault`) or the standard should be expected to be followed strictly.

### PR DESCRIPTION
**Pull request by erikzhang**
Fix #2450

### CODE REVIEW

**Comment by shargon** [comment]
Is not better to change the nep because all the json properties are in lowercase?

**Comment by erikzhang** [comment]
`isDefault` is never used. It is not worth modifying the NEP.

**Comment by shargon** [comment]
> isDefault is never used. It is not worth modifying the NEP.

neither to remove it?

**Review by shargon — APPROVED** [review]

**Comment by roman-khimov** [comment]
I can't say we're using it often, but we do have a test for it and there is some associated logic.

https://github.com/nspcc-dev/neo-go/blob/933743ce870915ed8b15073f5bae0c4bdc710157/pkg/wallet/testdata/wallet2.json#L61

**Comment by shargon** [comment]
I will add a UT

**Review by shargon — APPROVED** [review]

File: src/neo/Wallets/NEP6/NEP6Wallet.cs [hunk 1]
```diff
@@ -182,6 +182,20 @@ public override bool DeleteAccount(UInt160 scriptHash)
             }
         }
 
+        public WalletAccount GetAccount()
```
Comment (erikzhang) [inline src/neo/Wallets/NEP6/NEP6Wallet.cs:185]: I think we don't need `IsDefault` now. It is used in the old UTXO system.

Comment (roman-khimov) [reply src/neo/Wallets/NEP6/NEP6Wallet.cs:185]: Yes and no, I'd name this method `GetDefaultAccount` and as such it has its own use cases. A wallet can contain multiple addresses/keys and when using CLI I don't necessarily want to always add address to all commands, thus I can rely on default address being there and being used when no address is specified.

Comment (shargon) [reply src/neo/Wallets/NEP6/NEP6Wallet.cs:185]: We can change the name as @roman-khimov said, but I think that it could be useful use the default one in certain cases.

**Review by vncoelho — COMMENTED** [review]
I also think this can be removed for now and changed to other name.

File: src/neo/Wallets/NEP6/NEP6Wallet.cs (hunk 1 above)
Comment (erikzhang) [reply src/neo/Wallets/NEP6/NEP6Wallet.cs]: Renamed.
