### PR TITLE
Fixes #946

### LINKED ISSUE #946: Storage.Find returns items out of order
Say we store the following values
```C#
Storage.Put(Storage.CurrentContext, "AA_1", "1");
Storage.Put(Storage.CurrentContext, "AA_2", "2");
Storage.Put(Storage.CurrentContext, "AA_3", "3");
```

The following code 
```C#
Iterator<string, byte[]> si = Storage.Find(Storage.CurrentContext, "AA_");
Runtime.Notify("Starting");
while (si.Next())
{
   Runtime.Notify(si.Key);
}
Runtime.Notify("Done");
```
returns `AA_1`, `AA_2`, `AA_3` as expected.

Now add a `Storage_Get` before the `Find` call, like so:
```C#
Storage.Get(Storage.CurrentContext, "AA_1");
Iterator<string, byte[]> si = Storage.Find(Storage.CurrentContext, "AA_");
```
and the iterator now returns: `AA_2`, `AA_3`, `AA_1`

This is caused by line 126 of
https://github.com/neo-project/neo/blob/00f9c270de46c605b49990bc6d399e8f2419d65c/neo/IO/Caching/DataCache.cs#L121-L132
When the key is already found in its cache it actually skips it for the time being instead of immediate processing (checking if `DELETED`).

I think this is unexpected behaviour. I do not think that possible data caching needs to be taken into account by the smart contract programmer.  Any opinions?

### PR DESCRIPTION
**Pull request by erikzhang**
Close https://github.com/neo-project/neo/pull/947
Close https://github.com/neo-project/neo/issues/946

### CODE REVIEW

**Comment by shargon** [comment]
Stranger things 

image

**Comment by shargon** [comment]
Very stranger things ...

image

**Comment by shargon** [comment]
Grouping was playing with us 😆

File: neo/IO/Caching/DataCache.cs [hunk 1]
```diff
@@ -118,16 +118,65 @@ public void DeleteWhere(Func<TKey, TValue, bool> predicate)
...
+            using (var e2 = uncached.GetEnumerator())
+            {
+                (byte[] KeyBytes, TKey Key, TValue Item) i1, i2;
+                bool c1 = e1.MoveNext();
+                bool c2 = e2.MoveNext();
+                i1 = c1 ? e1.Current : default;
+                i2 = c2 ? e2.Current : default;
+                while (c1 || c2)
+                {
+                    if (!c2 || (c1 && ByteArrayComparer.Default.Compare(i1.KeyBytes, i2.KeyBytes) < 0))
```
Comment (shargon) [inline neo/IO/Caching/DataCache.cs]: i2 could be null

**Comment by erikzhang** [comment]
You can't remove grouping. Because it is stored with grouping and sorted with grouping in leveldb.

File: neo/IO/Caching/DataCache.cs (hunk 1 above)
Comment (erikzhang) [reply neo/IO/Caching/DataCache.cs]: It can't be.

**Comment by shargon** [comment]
The last fix was wrong.

image

This will produce that contract destroy or other calls fail, we need to call `Find` without the grouping.

https://github.com/neo-project/neo/blob/abda789f2de624acaf1f92d28be26bd6ebb9747b/neo/SmartContract/InteropService.cs#L540

In fact, we should remove the grouping, is very confuse.

**Comment by erikzhang** [comment]
Can you point out where it is wrong?

**Comment by shargon** [comment]
I think that we can remove the grouping like this

image

We know that this stream is fixed and is for the key, we could know the length.

**Comment by erikzhang** [comment]
The `BaseStream` may be a `NetworkStream`, and we can't get the `Length` from it.

**Comment by shargon** [comment]
Is wrong because you need to pass the arguments in the unit test with the group 

https://github.com/neo-project/neo/pull/950/commits/ac85174e37a60df083a4676228c57f39ee4257d0#diff-a3f0e31debacd97d5d593e04923f7f99R53

But in other calls within the code, it was called without grouping.

https://github.com/neo-project/neo/blob/abda789f2de624acaf1f92d28be26bd6ebb9747b/neo/SmartContract/InteropService.cs#L540

**Comment by shargon** [comment]
> The BaseStream may be a NetworkStream, and we can't get the Length from it.

I know it, but only in this case always will come from a storage (file).

**Comment by erikzhang** [comment]
> But in other calls within the code, it was called without grouping.

Only `StorageKey.Key` is grouped. `StorageKey.ScriptHash` is not grouped. So it's okay.

**Comment by erikzhang** [comment]
The only case that use `Storage.ScriptHash` in `Find()` is this:

https://github.com/neo-project/neo/blob/abda789f2de624acaf1f92d28be26bd6ebb9747b/neo/SmartContract/InteropService.NEO.cs#L341-L369

And it has processed the group correctly.

**Comment by shargon** [comment]
> Only StorageKey.Key is grouped. StorageKey.ScriptHash is not grouped. So it's okay.

I understand you, but is very weird, if i use the class, and i insert 0x00, and i need to find it with `new byte[21]`, i need to know how works the storage layer, and this is wrong.

**Comment by erikzhang** [comment]
I think you misunderstood. The first 20 bytes is the script hash. The last byte is the prefix.

**Comment by shargon** [comment]
Now I catch you 😆 , i was thinking in the key, but `Find` include the scriptHash and the key, so you are right!

File: neo/IO/ByteArrayComparer.cs [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+            int length = Math.Min(x.Length, y.Length);
+            for (int i = 0; i < length; i++)
+            {
+                int r = x[i].CompareTo(y[i]);
+                if (r != 0) return r;
+            }
+            return x.Length.CompareTo(y.Length);
+        }
+    }
+}
```
Comment (igormcoelho) [inline neo/IO/ByteArrayComparer.cs]: @rodoufu can you review this?

File: neo/IO/Caching/DataCache.cs [hunk 3]
```diff
@@ -118,16 +118,58 @@ public void DeleteWhere(Func<TKey, TValue, bool> predicate)
...
             lock (dictionary)
             {
-                foreach (var pair in FindInternal(key_prefix ?? new byte[0]))
-                    if (!dictionary.ContainsKey(pair.Key))
-                        yield return pair;
-                foreach (var pair in dictionary)
-                    if (pair.Value.State != TrackState.Deleted && (key_prefix == null || pair.Key.ToArray().Take(key_prefix.Length).SequenceEqual(key_prefix)))
-                        yield return new KeyValuePair<TKey, TValue>(pair.Key, pair.Value.Item);
+                cached = dictionary
+                    .Where(p => p.Value.State != TrackState.Deleted && (key_prefix == null || p.Key.ToArray().Take(key_prefix.Length).SequenceEqual(key_prefix)))
```
Comment (igormcoelho) [inline neo/IO/Caching/DataCache.cs]: Looks good to me, must do it in a deserialized format, to avoid different storage formats affecting Find.

File: neo/IO/Caching/DataCache.cs [hunk 4]
```diff
@@ -118,16 +118,58 @@ public void DeleteWhere(Func<TKey, TValue, bool> predicate)
...
+                    .Select(p =>
+                    (
+                        KeyBytes: p.Key.ToArray(),
+                        p.Key,
+                        p.Value.Item
+                    ))
+                    .OrderBy(p => p.KeyBytes, ByteArrayComparer.Default)
+                    .ToArray();
+            }
+            var uncached = FindInternal(key_prefix ?? new byte[0])
```
Comment (igormcoelho) [inline neo/IO/Caching/DataCache.cs]: Is this FindInternal implementation-specific? This is a good moment to avoid specific decisions affecting the outcome of Find.

File: neo/IO/Caching/DataCache.cs [hunk 5]
```diff
@@ -118,16 +118,58 @@ public void DeleteWhere(Func<TKey, TValue, bool> predicate)
...
+                .Where(p => !dictionary.ContainsKey(p.Key))
+                .Select(p =>
+                (
+                    KeyBytes: p.Key.ToArray(),
+                    p.Key,
+                    p.Value
+                ));
+            using (var e1 = cached.GetEnumerator())
```
Comment (igormcoelho) [inline neo/IO/Caching/DataCache.cs]: I think this "intercalation" strategy should be done in a separate function, so it's clear and also testable (perhaps useful in other situations too).

**Comment by igormcoelho** [comment]
Just to make sure, this sort is not considering Grouping anymore, just raw key, correct? Because grouping looks like an implementation-specific strategy, not a protocol level one.

**Comment by erikzhang** [comment]
> Just to make sure, this sort is not considering Grouping anymore, just raw key, correct?

I optimized it, and now our grouping algorithm will not affect the sorting.

File: neo/IO/Helper.cs [hunk 6]
```diff
@@ -92,17 +92,16 @@ public static byte[] ReadBytesWithGrouping(this BinaryReader reader)
         {
             using (MemoryStream ms = new MemoryStream())
             {
-                int padding = 0;
+                int count;
                 do
                 {
                     byte[] group = reader.ReadBytes(GroupingSizeInBytes);
```
Comment (shargon) [inline neo/IO/Helper.cs]: We should reuse this buffer
```
byte[] group=new byte[GroupSizeInBytes];
do{
read.Read(group,0,GroupSizeInBytes);

```

Comment (erikzhang) [reply neo/IO/Helper.cs]:
```c#
read.Read(group,0,GroupSizeInBytes);
```

This may read data less than `GroupSizeInBytes` and use an extra loop, which is very troublesome.
