### PR TITLE
Fix JsonSerializer

### LINKED ISSUE #2533: JSON Deserialize Slow
```
56010c015b0c135b5b5b5b5b5b5b5b5b5d5d5d5d5d5d5d5d5d2c1f60589d
604a8b5824fa0c135b5b5b5b5b5b5b5b5b5d5d5d5d5d5d5d5d5d2c1e6058
9d604a8b5824fa02ffbf04008d8b8b0c015d8b11c01f0c0f6a736f6e4465
73657269616c697a650c14c0ef39cee0e4e925c6c2a06a79e1440dd86fce
ac41627d5b5245
```

-----

#2530 #2527  Related

### PR DESCRIPTION
**Pull request by erikzhang**
Close #2533

### CODE REVIEW

**Comment by erikzhang** [comment]
@shargon @roman-khimov @Ashuaidehao

**Review by vang1ong7ang — DISMISSED** [review]

**Review by shargon — DISMISSED** [review]

File: src/neo/SmartContract/JsonSerializer.cs [hunk 1]
```diff
@@ -160,7 +169,10 @@ public static StackItem Deserialize(JObject json, ReferenceCounter referenceCoun
                     }
                 case JArray array:
                     {
-                        return new Array(referenceCounter, array.Select(p => Deserialize(p, referenceCounter)));
+                        List<StackItem> list = new();
```
Comment (shargon) [inline src/neo/SmartContract/JsonSerializer.cs:172]: Init capacity with `array.Count`?

**Review by roman-khimov — APPROVED** [review]

File: src/neo/SmartContract/JsonSerializer.cs (hunk 1 above)
Comment (erikzhang) [reply src/neo/SmartContract/JsonSerializer.cs]: Done.
