### PR TITLE
fix `Storage.Find`

### LINKED ISSUE #199: StorageIterator does not work
Please see https://github.com/neo-project/neo-devpack-dotnet/issues/19#issuecomment-373934451 for example reproduction.

The issue is that when doing the prefix building in `Storage.Find`, the contract script hash and storage prefix are simply concatenated. 
https://github.com/neo-project/neo/blob/f49f26604717579455691396adc301778c02d865/neo/SmartContract/StateReader.cs#L951

However, for Storage.Put/Get, I believe that serialization uses WriteVarBytes for the key portion:
https://github.com/neo-project/neo/blob/07dd1f5c9ca25ad3d2e91e97c55608d1cf938cbf/neo/Core/StorageKey.cs#L46

Which prefixes the length of the key:
https://github.com/neo-project/neo/blob/115a402478c00aaaa6f3ada671f14af69e0219cf/neo/IO/Helper.cs#L190

I think we can safely construct and then serialize a StorageKey instead to ensure they match?

Edit: Actually, the length prefix messes up the whole implementation - one way to make it work is by specifying key length, so the keys iterated on are constrained to a single length and must be known.

### PR DESCRIPTION
**Pull request by erikzhang**
fix #199

### CODE REVIEW

**Comment by erikzhang** [comment]
@RavenXce Can you review this?

**Comment by RavenXce** [comment]
I don't think this will work. As mentioned in the edit, the additional size prefix in `WriteVarBytes` during serialization causes iteration to not work unless the *full* key length is known.

By constructing the StorageKey with only the prefix, the calculated key size will never match the actual keys which will always have a longer length.

E.g.:
`Storage.Put(..., new byte[3] { 0x99, 0x01, 0x02 })` is stored to: `...[scripthash]03990102`

However previously,
`Storage.Find(..., new byte[2] { 0x99, 0x01 })` constructs a prefix: `...[scripthash]9901` (does not match due to missing `03`)

And with this change,
`Storage.Find(..., new byte[2] { 0x99, 0x01 })` constructs a prefix: `...[scripthash]029901` (does not match due to `02` instead of `03`)

---

So I managed to make it work only because all the keys I'm iterating over have a same known length, and so I can prepend the full key size as bytes directly.

Test code:
https://github.com/ConjurTech/switcheo/blob/master/switcheo/BrokerContract.cs#L367

**Comment by erikzhang** [comment]
You are right, it won't work...
Maybe we can use some sort of padding algorithm?

**Comment by erikzhang** [comment]
We can group key data and add a flag to each group that indicates whether it is the last group.

**Comment by erikzhang** [comment]
@RavenXce Will this work? Please review again.

File: neo/SmartContract/StateReader.cs [hunk 1]
```diff
@@ -948,8 +948,23 @@ protected virtual bool Storage_Find(ExecutionEngine engine)
...
+                        ms.Write(prefix, index, 16);
+                        ms.WriteByte(0);
+                        index += 16;
+                        remain -= 16;
+                    }
+                    if (remain > 0)
+                        ms.Write(prefix, index, remain);
+                    prefix_key = context.ScriptHash.ToArray().Concat(ms.ToArray()).ToArray();
+                }
+                StorageIterator iterator = new StorageIterator(Storages.Find(prefix_key).Where(p => p.Key.Key.Take(prefix.Length).SequenceEqual(prefix)).GetEnumerator());
```
Comment (RavenXce) [inline neo/SmartContract/StateReader.cs]: Is the `Where` part necessary? Since the prefix does not write any additional padding now

Comment (erikzhang) [reply neo/SmartContract/StateReader.cs]: Yes, it's necessary. Think of this, if the key is `0x112233`, the padded key is `0x11223300000000000000000000000000`. Then we find with the prefix `0x11223300`. This should find nothing. But if we don't have the `Where` part, it will match the padded key and return wrong results.
