### PR TITLE
[`Fix`]: getnativecontract throws null reference exception if contract not active

### LINKED ISSUE #3917: RPC `getnativecontract` will try to get unregistered native contract before harkfork height which cause null point return
**Describe the bug**
invoke `getnativecontract` before `HF_Echidna `, you will get:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -2147467261,
        "message": "Object reference not set to an instance of an object."
    }
}
```
Because `native notary contract` hasn't registered yet but `getnativecontract` is trying to getcontractstate.
It will return to work after `HF_Echidna`, but will always return this before `HF_Echidna`.

### PR DESCRIPTION
**Pull request by Wi1l-B0t**
# Description

Fixes #3917

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/Plugins/RpcServer/RpcServer.Blockchain.cs [hunk 1]
```diff
@@ -357,7 +362,8 @@ protected internal virtual JToken GetCandidates()
                 if (resultstack.Length > 0)
                 {
                     JArray jArray = new();
-                    var validators = NativeContract.NEO.GetNextBlockValidators(snapshot, system.Settings.ValidatorsCount) ?? throw new RpcException(RpcError.InternalServerError.WithData("Can't get next block validators."));
+                    var validators = NativeContract.NEO.GetNextBlockValidators(snapshot, system.Settings.ValidatorsCount)
```
Comment (Wi1l-B0t) [inline src/Plugins/RpcServer/RpcServer.Blockchain.cs:365]: These lines are too long.

File: src/Plugins/RpcServer/RpcServer.Blockchain.cs [hunk 2]
```diff
@@ -400,7 +406,12 @@ protected internal virtual JToken GetCommittee()
         [RpcMethodWithParams]
         protected internal virtual JToken GetNativeContracts()
         {
-            return new JArray(NativeContract.Contracts.Select(p => NativeContract.ContractManagement.GetContract(system.StoreView, p.Hash).ToJson()));
+            var storeView = system.StoreView;
+            var contractStates = NativeContract.Contracts
```
Comment (Wi1l-B0t) [inline src/Plugins/RpcServer/RpcServer.Blockchain.cs:410]: Fix on here

File: src/Plugins/RpcServer/RpcServer.Blockchain.cs (hunk 1 above)
Comment (AnnaShaleva) [reply src/Plugins/RpcServer/RpcServer.Blockchain.cs:365]: These changes are not related to the `getnativecontracts` problem, usually we use a separate PRs to fix this type of issues because it's a separate problem.

**Review by AnnaShaleva — COMMENTED** [review]
The fix itself is valid.

File: src/Plugins/RpcServer/RpcServer.Blockchain.cs (hunk 1 above)
Comment (Wi1l-B0t) [reply src/Plugins/RpcServer/RpcServer.Blockchain.cs:365]: > These changes are not related to the `getnativecontracts` problem, usually we use a separate PRs to fix this type of issues because it's a separate problem.

Just add a '\n'

**Review by shargon — APPROVED** [review]

File: src/Plugins/RpcServer/RpcServer.Blockchain.cs (hunk 1 above)
Comment (AnnaShaleva) [reply src/Plugins/RpcServer/RpcServer.Blockchain.cs:365]: Even just for this.

**Review by AnnaShaleva — APPROVED** [review]
