### PR TITLE
Policy inputs checks

### LINKED ISSUE #1937: Policy contract's SetMaxTransactionsPerBlock() doesn't check for Block.MaxTransactionsPerBlock
**Describe the bug**
Some policy values while being configurable are still limited by other hardcoded constraints, like `SetMaxBlockSize()` has to check the value passed against `Network.P2P.Message.PayloadMaxSize`, because it's not very useful to have blocks that couldn't be distributed via P2P.

`SetMaxTransactionsPerBlock()` at the moment allows any `uint` value to be set, but there are P2P limitations of `MaxContentsPerBlock` and `MaxTransactionsPerBlock` imposed by the `Block` class and setting policy value to some higher number would just create undeserializable block if anyone is to attempt to put this many transactions into it.

**Expected behavior**
`SetMaxTransactionsPerBlock()` should check the value passed against `Block.MaxTransactionsPerBlock`.

**(Optional) Additional context**
While we're here I'd also propose increasing `Block.MaxTransactionsPerBlock` two-fold. Given some typical 250-byte transactions a block with a length of `Network.P2P.Message.PayloadMaxSize` has enough space for just a little more than 128K of them.

Although even when the number of transactions per block is only limited by the payload size, some test results may look like this:

tpb_single_30_wrk_leveldb

Still, 64K is not allowing to use all of `PayloadMaxSize` capacity.

### PR DESCRIPTION
**Pull request by shargon**
Close #1937

### CODE REVIEW

File: src/neo/SmartContract/Native/PolicyContract.cs [hunk 1]
```diff
@@ -97,6 +99,7 @@ private bool SetMaxBlockSize(ApplicationEngine engine, uint value)
         [ContractMethod(0_03000000, CallFlags.AllowModifyStates)]
         private bool SetMaxTransactionsPerBlock(ApplicationEngine engine, uint value)
         {
+            if (value > Block.MaxTransactionsPerBlock) return false;
```
Comment (erikzhang) [inline src/neo/SmartContract/Native/PolicyContract.cs:102]: Throw exception?

Comment (shargon) [reply src/neo/SmartContract/Native/PolicyContract.cs]: done

File: src/neo/SmartContract/Native/PolicyContract.cs [hunk 2]
```diff
@@ -116,6 +119,7 @@ private bool SetMaxBlockSystemFee(ApplicationEngine engine, long value)
         [ContractMethod(0_03000000, CallFlags.AllowModifyStates)]
         private bool SetFeePerByte(ApplicationEngine engine, long value)
         {
+            if (value < 0) throw new ArgumentOutOfRangeException(nameof(value));
```
Comment (erikzhang) [inline src/neo/SmartContract/Native/PolicyContract.cs:122]:
```suggestion
            if (value < 0 || value > 1_00000000) throw new ArgumentOutOfRangeException(nameof(value));
```

**Comment by erikzhang** [comment]
UT failed.

**Review by erikzhang — DISMISSED** [review]

**Comment by roman-khimov** [comment]
Looks good, but how about 128K limit for `Block.MaxTransactionsPerBlock`?

**Comment by shargon** [comment]
> Looks good, but how about 128K limit for Block.MaxTransactionsPerBlock?

I think that this need more tests, it can be related with the time per block reduction issue. https://github.com/neo-project/neo/issues/375 @roman-khimov could you create a different issue for this?

**Comment by shargon** [comment]
UT Fixed

**Comment by roman-khimov** [comment]
I can, but to me it doesn't seem to be related to #375, it's just a matter of size match between `PayloadMaxSize` and `MaxTransactionsPerBlock`. With current `MaxTransactionsPerBlock` one block can't use all of `PayloadMaxSize` capacity irrespective of `MillisecondsPerBlock`.

**Comment by shargon** [comment]
For me it's related because both pretend to increase TPS changing the tx per block or the seconds per block, but it's more or less the same. Maybe I am wrong

**Review by erikzhang — APPROVED** [review]

**Comment by roman-khimov** [comment]
> both pretend to increase TPS

I don't. I'm specifically not mentioning TPS here, it's just a matter of match between different components of the system. There is a P2P payload limit, there has to be some, the maximum possible block size should probably match it and the maximum possible block size should be practically reachable with MaxTransactionsPerBlock, that's it.

> it's more or less the same

And #375 is more about latency to me. Of course, there is a natural `MemoryPoolMaxTransactions/MillisecondsPerBlock` ratio, but for mainnet/testnet this ratio doesn't seem to be a problem to me from the TPS perspective.

**Comment by shargon** [comment]
What do you think @erikzhang ?

```csharp
public const int MaxContentsPerBlock = 134_000; // (PayloadMaxSize=0x02000000)/(AverageTxSize=250)
```

**Comment by erikzhang** [comment]
`PayloadMaxSize` is not for blocks only.

**Comment by erikzhang** [comment]
And I want to limit the average block size to 256KB.
