### PR TITLE
fix: unexpected `InvalidOperationException` with circular reference in `ContractParamter.ToJson`

### LINKED ISSUE #3554: Unexpected `InvalidOperationException` with circular reference in `ContractParamter.ToJson`
**Describe the bug**
Similar to #3553 

```csharp
var map = new ContractParameter
{
   Type = ContractParameterType.Map,
   Value = new List<KeyValuePair<ContractParameter, ContractParameter>>
    {
        new(
            new ContractParameter { Type = ContractParameterType.Integer, Value = 1 },
            new ContractParameter { Type = ContractParameterType.Integer, Value = 2 }
        )
    }
};

var value = new List<ContractParameter> { map, map };
var item = new ContractParameter { Type = ContractParameterType.Array, Value = value };
var json = item.ToJson();
```

This `item` hasn't any circular reference, but `item.ToJson()` throws an `InvalidOperationException` with circular reference

### PR DESCRIPTION
**Pull request by nan01ab**
Fixes #3554 

Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
I'm not sure if we need a hardfork for this

**Comment by nan01ab** [comment]
> I'm not sure if we need a hardfork for this

The issue in `ContractParamter.ToJson` doesn't seem to be needed, and needs more checking  in the `StackItem`.

**Review by shargon — APPROVED** [review]

File: src/Neo/SmartContract/ContractParameter.cs [hunk 1]
```diff
@@ -182,6 +183,7 @@ private static JObject ToJson(ContractParameter parameter, HashSet<ContractParam
                             item["value"] = ToJson(p.Value, context);
                             return item;
                         }));
+                        context.Remove(parameter);
```
Comment (AnnaShaleva) [inline src/Neo/SmartContract/ContractParameter.cs:186]: It's a good fix, but how did you catch this issue? I'm asking because to me this bug seems a bit artificial, and it seems there's no way in real life to get such SC Param with cyclic reference.

**Review by AnnaShaleva — COMMENTED** [review]
> I'm not sure if we need a hardfork for this

The only place where we work with SC parameters inside VM is native Management's `deploy`/`update` methods (SC manifest contains SC parameters in the JSON form). But it's impossible to get cyclic reference there because we unmarshal manifest from JSON.

So to me we don't need a hardfork for that. LGTM.

File: src/Neo/SmartContract/ContractParameter.cs (hunk 1 above)
Comment (nan01ab) [reply src/Neo/SmartContract/ContractParameter.cs:186]: > It's a good fix, but how did you catch this issue? I'm asking because to me this bug seems a bit artificial, and it seems there's no way in real life to get such SC Param with cyclic reference from the node or dependent tools (except the tests, of course).

Code view.
Yes, there is currently no way to trigger this bug.

**Review by AnnaShaleva — APPROVED** [review]
